// Code generated by protoc-gen-ts. DO NOT EDIT.
// versions:
// - protoc-gen-ts v1.3.0
// - protoc             v5.27.0
// source: hello/hello.proto

interface CipherExampleReq{
}

interface MysqlExampleReq{
    name: string;
    age: number;
}

interface MysqlExampleResp{
    id: number;
    name: string;
    age: number;
    created_at: string;
    updated_at: string;
}

interface CipherExampleResp{
    aes_encrypt_value_in_plain_file: string;
    base64_encrypt_value_in_plain_file: string;
    plain_value_in_aes_encrypt_file: string;
    aes_encrypt_value_in_aes_encrypt_file: string;
    base64_encrypt_value_in_aes_encrypt_file: string;
}

interface SayReq{
    region_id: string;
    project_id: string;
    user_id: number;
    str_list: string;
    int_list: number;
    obj: message;
    objs: message;
    configs: message;
    page: number;
    size: number;
    sort: string;
    ok: boolean;
    int_optional_value: number;
    string_optional_value: string;
    kind: ;
    kinds: ;
    bytes_value: ;
    uint64_value: number;
    google_int64_value: message;
}

interface Configs{
    timeout: string;
    field_in_different_file_under_same_section: string;
    another_field_in_different_file_under_same_section: string;
}

interface SayObj{
    field_int: number;
    field_str: string;
}

