// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-rest v1.3.0
// - protoc             v5.27.0
// source: examples/protobuf/hello/hello.proto

package hello

import (
	rest "github.com/asjard/asjard/pkg/server/rest"
)

func _Hello_Say_RestHandler(ctx *rest.Context, srv any) {
	ctx.ReadAndWrite(func(rc *rest.Context, in any) (any, error) {
		return srv.(HelloServer).Say(rc, in.(*SayReq))
	}, new(SayReq))
}

// HelloRestServiceDesc is the rest.ServiceDesc for Hello service.
// It's only intended for direct use with rest.AddHandler,
// and not to be introspected or modified (even as a copy)
var HelloRestServiceDesc = rest.ServiceDesc{
	ServiceName: "api.v1.hello.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []rest.MethodDesc{
		{
			MethodName: "Say",
			Desc:       "say something.",
			Method:     "GET",
			Path:       "/v1",
			Handler:    _Hello_Say_RestHandler,
		},
		{
			MethodName: "Say",
			Desc:       "say something.",
			Method:     "POST",
			Path:       "/v1/region/{region_id}/project/{project_id}/user/{user_id}",
			Handler:    _Hello_Say_RestHandler,
		},
	},
}
