// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: protos-repo/gw/api/v1/gw.proto

package gw

import (
	_ "github.com/asjard/asjard/pkg/protobuf/httppb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceInstancesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// service name
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
}

func (x *ServiceInstancesReq) Reset() {
	*x = ServiceInstancesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_repo_gw_api_v1_gw_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInstancesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInstancesReq) ProtoMessage() {}

func (x *ServiceInstancesReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_repo_gw_api_v1_gw_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInstancesReq.ProtoReflect.Descriptor instead.
func (*ServiceInstancesReq) Descriptor() ([]byte, []int) {
	return file_protos_repo_gw_api_v1_gw_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceInstancesReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ServiceInstancesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instances []*ServiceInstancesResp_Instance `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
}

func (x *ServiceInstancesResp) Reset() {
	*x = ServiceInstancesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_repo_gw_api_v1_gw_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInstancesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInstancesResp) ProtoMessage() {}

func (x *ServiceInstancesResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_repo_gw_api_v1_gw_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInstancesResp.ProtoReflect.Descriptor instead.
func (*ServiceInstancesResp) Descriptor() ([]byte, []int) {
	return file_protos_repo_gw_api_v1_gw_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceInstancesResp) GetInstances() []*ServiceInstancesResp_Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type ServiceInstancesResp_Instance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InstanceId  string `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
}

func (x *ServiceInstancesResp_Instance) Reset() {
	*x = ServiceInstancesResp_Instance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_repo_gw_api_v1_gw_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInstancesResp_Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInstancesResp_Instance) ProtoMessage() {}

func (x *ServiceInstancesResp_Instance) ProtoReflect() protoreflect.Message {
	mi := &file_protos_repo_gw_api_v1_gw_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInstancesResp_Instance.ProtoReflect.Descriptor instead.
func (*ServiceInstancesResp_Instance) Descriptor() ([]byte, []int) {
	return file_protos_repo_gw_api_v1_gw_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ServiceInstancesResp_Instance) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceInstancesResp_Instance) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

var File_protos_repo_gw_api_v1_gw_proto protoreflect.FileDescriptor

var file_protos_repo_gw_api_v1_gw_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x72, 0x65, 0x70, 0x6f, 0x2f, 0x67, 0x77,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x67, 0x77, 0x1a, 0x25, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x73, 0x6a, 0x61, 0x72, 0x64, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x38, 0x0a, 0x13, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xae, 0x01, 0x0a,
	0x14, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x46, 0x0a, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x67, 0x77, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x1a, 0x4e, 0x0a,
	0x08, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x32, 0x6e, 0x0a,
	0x02, 0x47, 0x77, 0x12, 0x68, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x67, 0x77, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x67, 0x77, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x10, 0x82, 0xb5, 0x18,
	0x0c, 0x12, 0x0a, 0x2f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x42, 0x1a, 0x5a,
	0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x72, 0x65, 0x70, 0x6f, 0x2f, 0x67, 0x77, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x77, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_repo_gw_api_v1_gw_proto_rawDescOnce sync.Once
	file_protos_repo_gw_api_v1_gw_proto_rawDescData = file_protos_repo_gw_api_v1_gw_proto_rawDesc
)

func file_protos_repo_gw_api_v1_gw_proto_rawDescGZIP() []byte {
	file_protos_repo_gw_api_v1_gw_proto_rawDescOnce.Do(func() {
		file_protos_repo_gw_api_v1_gw_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_repo_gw_api_v1_gw_proto_rawDescData)
	})
	return file_protos_repo_gw_api_v1_gw_proto_rawDescData
}

var file_protos_repo_gw_api_v1_gw_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_repo_gw_api_v1_gw_proto_goTypes = []interface{}{
	(*ServiceInstancesReq)(nil),           // 0: api.v1.gw.ServiceInstancesReq
	(*ServiceInstancesResp)(nil),          // 1: api.v1.gw.ServiceInstancesResp
	(*ServiceInstancesResp_Instance)(nil), // 2: api.v1.gw.ServiceInstancesResp.Instance
}
var file_protos_repo_gw_api_v1_gw_proto_depIdxs = []int32{
	2, // 0: api.v1.gw.ServiceInstancesResp.instances:type_name -> api.v1.gw.ServiceInstancesResp.Instance
	0, // 1: api.v1.gw.Gw.GetServiceInstances:input_type -> api.v1.gw.ServiceInstancesReq
	1, // 2: api.v1.gw.Gw.GetServiceInstances:output_type -> api.v1.gw.ServiceInstancesResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_repo_gw_api_v1_gw_proto_init() }
func file_protos_repo_gw_api_v1_gw_proto_init() {
	if File_protos_repo_gw_api_v1_gw_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_repo_gw_api_v1_gw_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceInstancesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_repo_gw_api_v1_gw_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceInstancesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_repo_gw_api_v1_gw_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceInstancesResp_Instance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_repo_gw_api_v1_gw_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_repo_gw_api_v1_gw_proto_goTypes,
		DependencyIndexes: file_protos_repo_gw_api_v1_gw_proto_depIdxs,
		MessageInfos:      file_protos_repo_gw_api_v1_gw_proto_msgTypes,
	}.Build()
	File_protos_repo_gw_api_v1_gw_proto = out.File
	file_protos_repo_gw_api_v1_gw_proto_rawDesc = nil
	file_protos_repo_gw_api_v1_gw_proto_goTypes = nil
	file_protos_repo_gw_api_v1_gw_proto_depIdxs = nil
}
