// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: protos-repo/gw/api/v1/gw.proto

package gw

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Gw_GetServiceInstances_FullMethodName = "/api.v1.gw.Gw/GetServiceInstances"
)

// GwClient is the client API for Gw service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GwClient interface {
	// 获取服务的所有实例
	GetServiceInstances(ctx context.Context, in *ServiceInstancesReq, opts ...grpc.CallOption) (*ServiceInstancesResp, error)
}

type gwClient struct {
	cc grpc.ClientConnInterface
}

func NewGwClient(cc grpc.ClientConnInterface) GwClient {
	return &gwClient{cc}
}

func (c *gwClient) GetServiceInstances(ctx context.Context, in *ServiceInstancesReq, opts ...grpc.CallOption) (*ServiceInstancesResp, error) {
	out := new(ServiceInstancesResp)
	err := c.cc.Invoke(ctx, Gw_GetServiceInstances_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GwServer is the server API for Gw service.
// All implementations must embed UnimplementedGwServer
// for forward compatibility
type GwServer interface {
	// 获取服务的所有实例
	GetServiceInstances(context.Context, *ServiceInstancesReq) (*ServiceInstancesResp, error)
	mustEmbedUnimplementedGwServer()
}

// UnimplementedGwServer must be embedded to have forward compatible implementations.
type UnimplementedGwServer struct {
}

func (UnimplementedGwServer) GetServiceInstances(context.Context, *ServiceInstancesReq) (*ServiceInstancesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceInstances not implemented")
}
func (UnimplementedGwServer) mustEmbedUnimplementedGwServer() {}

// UnsafeGwServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GwServer will
// result in compilation errors.
type UnsafeGwServer interface {
	mustEmbedUnimplementedGwServer()
}

func RegisterGwServer(s grpc.ServiceRegistrar, srv GwServer) {
	s.RegisterService(&Gw_ServiceDesc, srv)
}

func _Gw_GetServiceInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInstancesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GwServer).GetServiceInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gw_GetServiceInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GwServer).GetServiceInstances(ctx, req.(*ServiceInstancesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Gw_ServiceDesc is the grpc.ServiceDesc for Gw service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gw_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.gw.Gw",
	HandlerType: (*GwServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceInstances",
			Handler:    _Gw_GetServiceInstances_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos-repo/gw/api/v1/gw.proto",
}
