// Code generated by protoc-gen-go-rest2grpc-gw. DO NOT EDIT.
// versions:
// - protoc-gen-go-rest2grpc-gw v1.3.0
// - protoc             v5.27.0
// source: protos-repo/gw/api/v1/gw.proto

package gw

import (
	context "context"
	bootstrap "github.com/asjard/asjard/core/bootstrap"
	client "github.com/asjard/asjard/core/client"
	config "github.com/asjard/asjard/core/config"
	grpc "github.com/asjard/asjard/pkg/client/grpc"
	rest "github.com/asjard/asjard/pkg/server/rest"
	sync "sync"
)

type GwAPI struct {
	UnimplementedGwServer
	client GwClient
}

var (
	gwAPI     *GwAPI
	gwAPIOnce sync.Once
)

func NewGwAPI() *GwAPI {
	gwAPIOnce.Do(func() {
		gwAPI = &GwAPI{}
		bootstrap.AddBootstrap(gwAPI)
	})
	return gwAPI
}
func (api *GwAPI) Start() error {
	conn, err := client.NewClient(grpc.Protocol, config.GetString("asjard.topology.services.gw.name", "svc-gw-api")).Conn()
	if err != nil {
		return err
	}
	api.client = NewGwClient(conn)
	return nil
}
func (api *GwAPI) Stop() {
}

// 获取服务的所有实例
func (api *GwAPI) GetServiceInstances(ctx context.Context, in *ServiceInstancesReq) (*ServiceInstancesResp, error) {
	return api.client.GetServiceInstances(ctx, in)
}
func (api *GwAPI) RestServiceDesc() *rest.ServiceDesc {
	return &GwRestServiceDesc
}
