// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// versions:
// - protoc-gen-go-validate v1.0.1
// - protoc             v5.27.0
// source: protos-repo/gw/api/v1/gw.proto

package gw

import (
	validatepb "github.com/asjard/asjard/pkg/protobuf/validatepb"
)

func (m *ServiceInstancesReq) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

func (m *ServiceInstancesResp_Instance) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

func (m *ServiceInstancesResp) IsValid(parentFieldName, fullMethod string) error {
	for _, fm := range m.Instances {
		if err := fm.IsValid(validatepb.ValidateFieldName(parentFieldName, "instances"), fullMethod); err != nil {
			return err
		}
	}
	return nil
}
