/*
 *
 * Copyright 2024 ASJARD authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

const (
	// FileDescriptorProto.package field number
	fileDescriptorProtoPackageFieldNumber = 2
	// FileDescriptorProto.syntax field number
	fileDescriptorProtoSyntaxFieldNumber = 12
)

type TsGenerator struct {
	plugin     *protogen.Plugin
	gen        *protogen.GeneratedFile
	file       *protogen.File
	openapiVar string
}

func NewGwGenerator(plugin *protogen.Plugin, file *protogen.File) *TsGenerator {
	return &TsGenerator{
		plugin: plugin,
		file:   file,
	}
}

func (g *TsGenerator) Run() *protogen.GeneratedFile {
	if len(g.file.Services) == 0 {
		return nil
	}
	g.gen = g.plugin.NewGeneratedFile(g.file.GeneratedFilenamePrefix+".d.ts", g.file.GoImportPath)

	g.genLeadingComments(g.file.Desc.SourceLocations().ByPath(protoreflect.SourcePath{fileDescriptorProtoSyntaxFieldNumber}))
	g.gen.P("// Code generated by ", name, ". DO NOT EDIT.")
	g.gen.P("// versions:")
	g.gen.P("// - ", name, " v", version)
	g.gen.P("// - protoc             ", g.protocVersion())
	if g.file.Proto.GetOptions().GetDeprecated() {
		g.gen.P("// ", g.file.Desc.Path(), " is a deprecated file.")
	} else {
		g.gen.P("// source: ", g.file.Desc.Path())
	}
	g.gen.P()

	// Attach all comments associated with the package field.
	g.genLeadingComments(g.file.Desc.SourceLocations().ByPath(protoreflect.SourcePath{fileDescriptorProtoPackageFieldNumber}))

	g.genFileContent()
	return g.gen
}

func (g *TsGenerator) genFileContent() {
	for _, message := range g.file.Messages {
		g.genMessage(message)
	}
}

func (g *TsGenerator) genService(service *protogen.Service) {
	for _, method := range service.Methods {
		g.genServiceMethod(service, method)
	}
}

func (g *TsGenerator) genServiceMethod(service *protogen.Service, method *protogen.Method) {
}

func (g *TsGenerator) genLeadingComments(loc protoreflect.SourceLocation) {
	for _, s := range loc.LeadingDetachedComments {
		g.gen.P(protogen.Comments(s))
		g.gen.P()
	}
	if s := loc.LeadingComments; s != "" {
		g.gen.P(protogen.Comments(s))
		g.gen.P()
	}
}

func (g *TsGenerator) genComment(comments protogen.CommentSet) {
	if comments.Leading != "" {
		g.gen.P("//")
		g.gen.P(strings.TrimSpace(comments.Leading.String()))
	}
}

func (g *TsGenerator) protocVersion() string {
	v := g.plugin.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

func (g *TsGenerator) genMessage(message *protogen.Message) {
	g.gen.P("interface ", message.GoIdent, "{")
	for _, field := range message.Fields {
		g.gen.P("    ", field.Desc.Name(), ": ", g.tsKindString(field.Desc.Kind()), ";")
	}
	g.gen.P("}")
	g.gen.P()
}

func (g *TsGenerator) tsKindString(kind protoreflect.Kind) string {
	switch kind {
	case protoreflect.BoolKind:
		return "boolean"
	case protoreflect.StringKind, protoreflect.Int64Kind:
		return "string"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Uint32Kind,
		protoreflect.Fixed32Kind, protoreflect.Sfixed32Kind, protoreflect.FloatKind:
		return "number"
	case protoreflect.MessageKind:
		return kind.String()
	}
	return ""
}
