// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// versions:
// - protoc-gen-go-validate v1.0.1
// - protoc             v5.27.0
// source: protos-repo/common/common.proto

package common

import (
	status "github.com/asjard/asjard/core/status"
	validatepb "github.com/asjard/asjard/pkg/protobuf/validatepb"
	codes "google.golang.org/grpc/codes"
)

func (m *Empty) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

func (m *ReqWithId) IsValid(parentFieldName, fullMethod string) error {
	v := validatepb.DefaultValidator
	if err := v.Var(m.Id, "required"); err != nil {
		return status.Errorf(codes.InvalidArgument, "validation field '%s' on 'required' fail", validatepb.ValidateFieldName(parentFieldName, "id"))
	}
	return nil
}

func (m *ReqWithName) IsValid(parentFieldName, fullMethod string) error {
	v := validatepb.DefaultValidator
	if err := v.Var(m.Name, "required"); err != nil {
		return status.Errorf(codes.InvalidArgument, "validation field '%s' on 'required' fail", validatepb.ValidateFieldName(parentFieldName, "name"))
	}
	return nil
}
