version: "3"
networks:
  example:

services:
  etcd:
    image: milvusdb/etcd:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 2379:2379
    networks:
      - example
    environment:
      ALLOW_NONE_AUTHENTICATION: yes
  mariadb:
    image: mariadb
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: example-database
      TZ: "Asia/Shanghai"
  amqp:
    image: rabbitmq:3.13.7-management-alpine
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    ports:
      - 5672:5672
      - 15692:15692
      - 15672:15672
  redis:
    image: redis
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    ports:
      - 6379:6379
  jeager:
    image: jaegertracing/all-in-one:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    ports:
      - 4318:4318
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9441
  prometheus:
    image: ubuntu/prometheus:3-24.04_stable
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    volumes:
      - ./.github/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    external_links:
      - asjard-pushgateway-1:pushgateway
  pushgateway:
    image: prom/pushgateway:master
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 9091:9091
    networks:
      - example
  consul:
    image: consul:1.15.4
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 8500:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0
    networks:
      - example
