version: "3"
networks:
  example:

services:
  etcd:
    image: milvusdb/etcd:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 2379:2379
    networks:
      - example
    environment:
      ALLOW_NONE_AUTHENTICATION: yes
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 5s
      timeout: 3s
      retries: 20
  mariadb:
    image: mariadb
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: example-database
      TZ: "Asia/Shanghai"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 30
  amqp:
    image: rabbitmq:3.13.7-management-alpine
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    ports:
      - 5672:5672
      - 15692:15692
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 30
  # rabbitmq:
  #   image: rabbitmq:4.3-rc-management-delayed-message-plugin
  #   restart: always
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: "10m"
  #       max-file: "10"
  #   networks:
  #     - example
  #   ports:
  #     - 5672:5672
  #     - 15692:15692
  #     - 15672:15672
  redis:
    image: redis
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
  jeager:
    image: jaegertracing/all-in-one:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    ports:
      - 4318:4318
      - 16686:16686
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9441
  prometheus:
    image: ubuntu/prometheus:3-24.04_stable
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - example
    volumes:
      - ./.github/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    external_links:
      - asjard-pushgateway-1:pushgateway
  pushgateway:
    image: prom/pushgateway:master
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 9091:9091
    networks:
      - example
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9091/-/ready"]
      interval: 5s
      timeout: 3s
      retries: 20
  consul:
    image: consul:1.15.4
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 8500:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0
    networks:
      - example
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 5s
      timeout: 3s
      retries: 20
