// Code generated by protoc-gen-go-rest2grpc-gw. DO NOT EDIT.
// versions:
// - protoc-gen-go-rest2grpc-gw v1.3.0
// - protoc             v5.27.0
// source: third_party/github.com/asjard/protobuf/health.proto

package healthpb

import (
	context "context"
	client "github.com/asjard/asjard/core/client"
	config "github.com/asjard/asjard/core/config"
	grpc "github.com/asjard/asjard/pkg/client/grpc"
	rest "github.com/asjard/asjard/pkg/server/rest"
)

type HealthAPI struct {
	UnimplementedHealthServer
	client HealthClient
}

func (api *HealthAPI) Bootstrap() error {
	conn, err := client.NewClient(grpc.Protocol, config.GetString("asjard.topology.services.health.name", "health")).Conn()
	if err != nil {
		return err
	}
	api.client = NewHealthClient(conn)
	return nil
}
func (api *HealthAPI) Shutdown() {
}

// healthCheck
func (api *HealthAPI) Check(ctx context.Context, in *HealthCheckRequest) (*HealthCheckResponse, error) {
	return api.client.Check(ctx, in)
}
func (api *HealthAPI) RestServiceDesc() *rest.ServiceDesc {
	return &HealthRestServiceDesc
}
