// Code generated by protoc-gen-go-rest2grpc-gw. DO NOT EDIT.
// versions:
// - protoc-gen-go-rest2grpc-gw v1.3.0
// - protoc             v5.27.0
// source: protos-repo/example/openapi/v1/user.proto

package user

import (
	context "context"
	bootstrap "github.com/asjard/asjard/core/bootstrap"
	client "github.com/asjard/asjard/core/client"
	config "github.com/asjard/asjard/core/config"
	grpc "github.com/asjard/asjard/pkg/client/grpc"
	rest "github.com/asjard/asjard/pkg/server/rest"
	common "protos-repo/common/common"
	sync "sync"
)

type UserAPI struct {
	UnimplementedUserServer
	client UserClient
}

var (
	userAPI     *UserAPI
	userAPIOnce sync.Once
)

func NewUserAPI() *UserAPI {
	userAPIOnce.Do(func() {
		userAPI = &UserAPI{}
		bootstrap.AddBootstrap(userAPI)
	})
	return userAPI
}
func (api *UserAPI) Start() error {
	conn, err := client.NewClient(grpc.Protocol, config.GetString("asjard.topology.services.docs.openapi.name", "svc-example-openapi")).Conn()
	if err != nil {
		return err
	}
	api.client = NewUserClient(conn)
	return nil
}
func (api *UserAPI) Stop() {
}

// Get retrieves a single user by their primary identifier (username/key).
// Workflow: LocalCache -> Redis -> Database.
// Failure to find a record results in a gRPC NOT_FOUND (HTTP 404).
func (api *UserAPI) Get(ctx context.Context, in *common.ReqWithName) (*UserInfo, error) {
	return api.client.Get(ctx, in)
}
func (api *UserAPI) RestServiceDesc() *rest.ServiceDesc {
	return &UserRestServiceDesc
}
