// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// versions:
// - protoc-gen-go-validate v1.0.1
// - protoc             v5.27.0
// source: protos-repo/example/openapi/v1/user.proto

package user

// IsValid Params validate
func (m *UserInfo) IsValid(parentFieldName, fullMethod string) error {
	return nil
}
