// Code generated by protoc-gen-go-rest2grpc-gw. DO NOT EDIT.
// versions:
// - protoc-gen-go-rest2grpc-gw v1.3.0
// - protoc             v5.27.0
// source: protos-repo/example/api/v1/user.proto

package user

import (
	context "context"
	bootstrap "github.com/asjard/asjard/core/bootstrap"
	client "github.com/asjard/asjard/core/client"
	config "github.com/asjard/asjard/core/config"
	grpc "github.com/asjard/asjard/pkg/client/grpc"
	rest "github.com/asjard/asjard/pkg/server/rest"
	common "protos-repo/common/common"
	sync "sync"
)

type UserAPI struct {
	UnimplementedUserServer
	client UserClient
}

var (
	userAPI     *UserAPI
	userAPIOnce sync.Once
)

func NewUserAPI() *UserAPI {
	userAPIOnce.Do(func() {
		userAPI = &UserAPI{}
		bootstrap.AddBootstrap(userAPI)
	})
	return userAPI
}
func (api *UserAPI) Start() error {
	conn, err := client.NewClient(grpc.Protocol, config.GetString("asjard.topology.services.example.name", "svc-example-api")).Conn()
	if err != nil {
		return err
	}
	api.client = NewUserClient(conn)
	return nil
}
func (api *UserAPI) Stop() {
}

// Create persists a new user record.
// In Asjard, this method typically uses 'SetData' to pre-allocate IDs
// and initialize the cache state to prevent early cache-miss storms.
func (api *UserAPI) Create(ctx context.Context, in *UserReq) (*common.Empty, error) {
	return api.client.Create(ctx, in)
}

// Get retrieves a single user by their primary identifier (username/key).
// Workflow: LocalCache -> Redis -> Database.
// Failure to find a record results in a gRPC NOT_FOUND (HTTP 404).
func (api *UserAPI) Get(ctx context.Context, in *common.ReqWithName) (*UserInfo, error) {
	return api.client.Get(ctx, in)
}

// Update modifies an existing user profile.
// Triggers the 'Delayed Double Delete' strategy via Asjard's Time Wheel
// to ensure consistency across distributed LocalCache nodes.
func (api *UserAPI) Update(ctx context.Context, in *UserReq) (*common.Empty, error) {
	return api.client.Update(ctx, in)
}

// Del removes the user record from the persistent store and
// synchronously purges associated entries from all cache levels.
func (api *UserAPI) Del(ctx context.Context, in *common.ReqWithName) (*common.Empty, error) {
	return api.client.Del(ctx, in)
}

// Search filters users with pagination support.
// Note: Search results are typically cached at the 'Group' level
// with shorter TTLs compared to individual 'Get' records.
func (api *UserAPI) Search(ctx context.Context, in *UserSearchReq) (*UserList, error) {
	return api.client.Search(ctx, in)
}
func (api *UserAPI) RestServiceDesc() *rest.ServiceDesc {
	return &UserRestServiceDesc
}
