// Code generated by protoc-gen-go-amqp. DO NOT EDIT.
// versions:
// - protoc-gen-go-amqp v1.0.0
// - protoc             v5.27.0
// source: protos-repo/example/api/v1/user.proto

package user

import (
	bootstrap "github.com/asjard/asjard/core/bootstrap"
	xamqp1 "github.com/asjard/asjard/pkg/server/xamqp"
	xamqp "github.com/asjard/asjard/pkg/stores/xamqp"
	amqp091_go "github.com/rabbitmq/amqp091-go"
	sync "sync"
)

type UserAmqpClientOptions struct {
	clientName string
}
type UserAmqpClientOption func(opts *UserAmqpClientOptions)

func UserAmqpClientWithClient(clientName string) UserAmqpClientOption {
	return func(opts *UserAmqpClientOptions) {
		if clientName != "" {
			opts.clientName = clientName
		}
	}
}

type UserAmqpClient struct {
	*xamqp.ClientConn
	options *UserAmqpClientOptions
}

var (
	userAmqpClient     *UserAmqpClient
	userAmqpClientOnce sync.Once
)

func NewUserAmqpClient(opts ...UserAmqpClientOption) *UserAmqpClient {
	userAmqpClientOnce.Do(func() {
		options := &UserAmqpClientOptions{
			clientName: "default",
		}
		for _, opt := range opts {
			opt(options)
		}
		userAmqpClient = &UserAmqpClient{
			options: options,
		}
		bootstrap.AddBootstrap(userAmqpClient)
	})
	return userAmqpClient
}
func (c *UserAmqpClient) Start() error {
	conn, err := xamqp.Client(xamqp.WithClientName(c.options.clientName))
	if err != nil {
		return err
	}
	c.ClientConn = conn
	ch, err := conn.Channel()
	if err != nil {
		return err
	}
	defer ch.Close()
	for _, method := range UserAmqpServiceDesc.Methods {
		if method.Queue != "" {
			if _, err := ch.QueueDeclare(method.Queue, method.Durable, method.AutoDelete, method.Exclusive, method.NoWait, method.Table); err != nil {
				return err
			}
		}
		if method.Exchange != "" {
			if err := ch.ExchangeDeclare(method.Exchange, method.Kind, method.Durable, method.AutoDelete, method.Internal, method.NoWait, method.Table); err != nil {
				return err
			}
			if method.Queue != "" {
				if err := ch.QueueBind(method.Queue, method.Route, method.Exchange, method.NoWait, method.Table); err != nil {
					return err
				}
			}
		}
	}
	return nil
}
func (c *UserAmqpClient) Stop() {}
func (c *UserAmqpClient) GetChannel() (*amqp091_go.Channel, error) {
	return c.ClientConn.Channel()
}

const ()

// UserAmqpServiceDesc is the xamqp1.ServiceDesc for User service.
// It's only intended for direct use with xamqp1.AddHandler,
// and not to be introspected or modified (even as a copy)
//
// User example
// User service handles lifecycle management and data retrieval for User entities.
// It integrates with the Asjard Store layer to provide transparent caching
// and high-concurrency protection (Singleflight).
var UserAmqpServiceDesc = xamqp1.ServiceDesc{
	ServiceName: "api.v1.example.docs.User",
	HandlerType: (*UserServer)(nil),
	Methods:     []xamqp1.MethodDesc{},
}
