// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// versions:
// - protoc-gen-go-validate v1.0.1
// - protoc             v5.27.0
// source: protos-repo/example/api/v1/user.proto

package user

import (
	status "github.com/asjard/asjard/core/status"
	validatepb "github.com/asjard/asjard/pkg/protobuf/validatepb"
	codes "google.golang.org/grpc/codes"
)

func (m *UserCreditCardReq) IsValid(parentFieldName, fullMethod string) error {
	v := validatepb.DefaultValidator
	if err := v.Var(m.Username, "required"); err != nil {
		return status.Errorf(codes.InvalidArgument, "validation field '%s' on 'required' fail", validatepb.ValidateFieldName(parentFieldName, "username"))
	}
	if err := v.Var(m.Number, "required,max=100"); err != nil {
		return status.Errorf(codes.InvalidArgument, "validation field '%s' on 'required,max=100' fail", validatepb.ValidateFieldName(parentFieldName, "number"))
	}
	return nil
}

func (m *UserCreditCardInfo) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

func (m *UserCreditCardList) IsValid(parentFieldName, fullMethod string) error {
	for _, fm := range m.List {
		if err := fm.IsValid(validatepb.ValidateFieldName(parentFieldName, "list"), fullMethod); err != nil {
			return err
		}
	}
	return nil
}

// IsValid Params validate
// UserReq represents the input payload for creating or updating a user.
// Validation is enforced by the Asjard Validation Interceptor before reaching the handler.
func (m *UserReq) IsValid(parentFieldName, fullMethod string) error {
	v := validatepb.DefaultValidator
	if err := v.Var(m.Username, "required,max=50"); err != nil {
		return status.Errorf(codes.InvalidArgument, "validation field '%s' on 'required,max=50' fail", validatepb.ValidateFieldName(parentFieldName, "username"))
	}
	if err := v.Var(m.Age, "min=0,max=200"); err != nil {
		return status.Errorf(codes.InvalidArgument, "validation field '%s' on 'min=0,max=200' fail", validatepb.ValidateFieldName(parentFieldName, "age"))
	}
	return nil
}

// IsValid Params validate
// UserInfo represents the data structure returned for single or list queries.
func (m *UserInfo) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

// IsValid Params validate
// UserSearchReq provides parameters for complex queries.
func (m *UserSearchReq) IsValid(parentFieldName, fullMethod string) error {
	v := validatepb.DefaultValidator
	if err := v.Var(m.Page, "min=0"); err != nil {
		return status.Errorf(codes.InvalidArgument, "validation field '%s' on 'min=0' fail", validatepb.ValidateFieldName(parentFieldName, "page"))
	}
	if err := v.Var(m.Size, "min=5"); err != nil {
		return status.Errorf(codes.InvalidArgument, "validation field '%s' on 'min=5' fail", validatepb.ValidateFieldName(parentFieldName, "size"))
	}
	if err := v.Var(m.Sort, "sortFields=created_at"); err != nil {
		return status.Errorf(codes.InvalidArgument, "validation field '%s' on 'sortFields=created_at' fail", validatepb.ValidateFieldName(parentFieldName, "sort"))
	}
	return nil
}

// IsValid Params validate
// UserList is the standard response envelope for paginated Search results.
func (m *UserList) IsValid(parentFieldName, fullMethod string) error {
	for _, fm := range m.List {
		if err := fm.IsValid(validatepb.ValidateFieldName(parentFieldName, "list"), fullMethod); err != nil {
			return err
		}
	}
	return nil
}
