package interceptors

import (
	"context"

	"github.com/asjard/asjard/core/client"
	"github.com/asjard/asjard/pkg/client/grpc"
	"github.com/asjard/asjard/pkg/protobuf/validatepb"
)

const (
	// ValidateInterceptorName is the unique identifier for the parameter validation interceptor.
	ValidateInterceptorName = "validate"
)

// Validate implements client-side parameter checking.
type Validate struct{}

func init() {
	// Register the validation interceptor specifically for the gRPC protocol.
	client.AddInterceptor(ValidateInterceptorName, NewValidateInterceptor, grpc.Protocol)
}

// Name returns the interceptor's registration name.
func (r *Validate) Name() string {
	return ValidateInterceptorName
}

// NewValidateInterceptor initializes a new instance of the validation interceptor.
func NewValidateInterceptor() (client.ClientInterceptor, error) {
	return &Validate{}, nil
}

// Interceptor provides the logic to verify request data before the remote call.
func (r *Validate) Interceptor() client.UnaryClientInterceptor {
	return func(ctx context.Context, method string, req, reply any, cc client.ClientConnInterface, invoker client.UnaryInvoker) error {
		// Check if the request object implements the Validater interface.
		// This interface is typically generated by protoc-gen-validate or similar tools.
		if v, ok := req.(validatepb.Validater); ok {
			// Execute the validation logic.
			// If validation fails, return the error immediately and skip the network call.
			if err := v.IsValid("", method); err != nil {
				return err
			}
		}

		// If validation passes or the request is not "validatable", proceed to the next interceptor.
		return invoker(ctx, method, req, reply, cc)
	}
}
