// Code generated by protoc-gen-go-amqp. DO NOT EDIT.
// versions:
// - protoc-gen-go-amqp v1.0.0
// - protoc             v5.27.0
// source: protos-repo/example/api/v1/config.proto

// Package naming convention: api.{version}.{app}.{module}

package config

import (
	bootstrap "github.com/asjard/asjard/core/bootstrap"
	xamqp1 "github.com/asjard/asjard/pkg/server/xamqp"
	xamqp "github.com/asjard/asjard/pkg/stores/xamqp"
	amqp091_go "github.com/rabbitmq/amqp091-go"
	sync "sync"
)

type ConfigAmqpClientOptions struct {
	clientName string
}
type ConfigAmqpClientOption func(opts *ConfigAmqpClientOptions)

func ConfigAmqpClientWithClient(clientName string) ConfigAmqpClientOption {
	return func(opts *ConfigAmqpClientOptions) {
		if clientName != "" {
			opts.clientName = clientName
		}
	}
}

type ConfigAmqpClient struct {
	*xamqp.ClientConn
	options *ConfigAmqpClientOptions
}

var (
	configAmqpClient     *ConfigAmqpClient
	configAmqpClientOnce sync.Once
)

func NewConfigAmqpClient(opts ...ConfigAmqpClientOption) *ConfigAmqpClient {
	configAmqpClientOnce.Do(func() {
		options := &ConfigAmqpClientOptions{
			clientName: "default",
		}
		for _, opt := range opts {
			opt(options)
		}
		configAmqpClient = &ConfigAmqpClient{
			options: options,
		}
		bootstrap.AddBootstrap(configAmqpClient)
	})
	return configAmqpClient
}
func (c *ConfigAmqpClient) Start() error {
	conn, err := xamqp.Client(xamqp.WithClientName(c.options.clientName))
	if err != nil {
		return err
	}
	c.ClientConn = conn
	ch, err := conn.Channel()
	if err != nil {
		return err
	}
	defer ch.Close()
	for _, method := range ConfigAmqpServiceDesc.Methods {
		if method.Queue != "" {
			if _, err := ch.QueueDeclare(method.Queue, method.Durable, method.AutoDelete, method.Exclusive, method.NoWait, method.Table); err != nil {
				return err
			}
		}
		if method.Exchange != "" {
			if err := ch.ExchangeDeclare(method.Exchange, method.Kind, method.Durable, method.AutoDelete, method.Internal, method.NoWait, method.Table); err != nil {
				return err
			}
			if method.Queue != "" {
				if err := ch.QueueBind(method.Queue, method.Route, method.Exchange, method.NoWait, method.Table); err != nil {
					return err
				}
			}
		}
	}
	return nil
}
func (c *ConfigAmqpClient) Stop() {}
func (c *ConfigAmqpClient) GetChannel() (*amqp091_go.Channel, error) {
	return c.ClientConn.Channel()
}

const ()

// ConfigAmqpServiceDesc is the xamqp1.ServiceDesc for Config service.
// It's only intended for direct use with xamqp1.AddHandler,
// and not to be introspected or modified (even as a copy)
//
// Config Example
// Config service handles application configuration retrieval and management.
var ConfigAmqpServiceDesc = xamqp1.ServiceDesc{
	ServiceName: "api.v1.example.docs.Config",
	HandlerType: (*ConfigServer)(nil),
	Methods:     []xamqp1.MethodDesc{},
}
