// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// versions:
// - protoc-gen-go-validate v1.0.1
// - protoc             v5.27.0
// source: protos-repo/example/api/v1/config.proto

// Package naming convention: api.{version}.{app}.{module}

package config

import (
	status "github.com/asjard/asjard/core/status"
	validatepb "github.com/asjard/asjard/pkg/protobuf/validatepb"
	codes "google.golang.org/grpc/codes"
)

func (m *ConfigGetReq) IsValid(parentFieldName, fullMethod string) error {
	v := validatepb.DefaultValidator
	if err := v.Var(m.Page, "min=0"); err != nil {
		return status.Errorf(codes.InvalidArgument, "validation field '%s' on 'min=0' fail", validatepb.ValidateFieldName(parentFieldName, "page"))
	}
	if err := v.Var(m.Size, "min=5,max=100"); err != nil {
		return status.Errorf(codes.InvalidArgument, "validation field '%s' on 'min=5,max=100' fail", validatepb.ValidateFieldName(parentFieldName, "size"))
	}
	if err := v.Var(m.Sort, "sortFields=created_at"); err != nil {
		return status.Errorf(codes.InvalidArgument, "validation field '%s' on 'sortFields=created_at' fail", validatepb.ValidateFieldName(parentFieldName, "sort"))
	}
	return nil
}

// IsValid Params validate
// Sub-object for structured configuration fields
func (m *ConfigGetResp_Obj) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

// IsValid Params validate
// Configs group: Illustrates Asjard's "Configuration Aggregation" capability.
func (m *ConfigGetResp_Configs) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

// IsValid Params validate
// Instance metadata: Used for service discovery and runtime inspection.
func (m *ConfigGetResp_Instance) IsValid(parentFieldName, fullMethod string) error {
	return nil
}

// IsValid Params validate
// ConfigGetResp defines a comprehensive configuration response structure.
// This message showcases Asjard's ability to handle complex nested data.
func (m *ConfigGetResp) IsValid(parentFieldName, fullMethod string) error {
	if m.Obj != nil {
		if err := m.Obj.IsValid(validatepb.ValidateFieldName(parentFieldName, "obj"), fullMethod); err != nil {
			return err
		}
	}
	for _, fm := range m.Objs {
		if err := fm.IsValid(validatepb.ValidateFieldName(parentFieldName, "objs"), fullMethod); err != nil {
			return err
		}
	}
	if m.Configs != nil {
		if err := m.Configs.IsValid(validatepb.ValidateFieldName(parentFieldName, "configs"), fullMethod); err != nil {
			return err
		}
	}
	if _, ok := ConfigGetResp_Kind_name[int32(m.Kind)]; !ok {
		return status.Errorf(codes.InvalidArgument, "invalid %s", validatepb.ValidateFieldName(parentFieldName, "kind"))
	}
	if m.Instance != nil {
		if err := m.Instance.IsValid(validatepb.ValidateFieldName(parentFieldName, "instance"), fullMethod); err != nil {
			return err
		}
	}
	return nil
}

// IsValid Params validate
// Response structure for decryption requests
func (m *ConfigDecryptResp) IsValid(parentFieldName, fullMethod string) error {
	return nil
}
