// Code generated by protoc-gen-go-rest2grpc-gw. DO NOT EDIT.
// versions:
// - protoc-gen-go-rest2grpc-gw v1.3.0
// - protoc             v5.27.0
// source: protos-repo/example/api/v1/config.proto

// Package naming convention: api.{version}.{app}.{module}

package config

import (
	context "context"
	bootstrap "github.com/asjard/asjard/core/bootstrap"
	client "github.com/asjard/asjard/core/client"
	config "github.com/asjard/asjard/core/config"
	grpc "github.com/asjard/asjard/pkg/client/grpc"
	rest "github.com/asjard/asjard/pkg/server/rest"
	common "protos-repo/common/common"
	sync "sync"
)

type ConfigAPI struct {
	UnimplementedConfigServer
	client ConfigClient
}

var (
	configAPI     *ConfigAPI
	configAPIOnce sync.Once
)

func NewConfigAPI() *ConfigAPI {
	configAPIOnce.Do(func() {
		configAPI = &ConfigAPI{}
		bootstrap.AddBootstrap(configAPI)
	})
	return configAPI
}
func (api *ConfigAPI) Start() error {
	conn, err := client.NewClient(grpc.Protocol, config.GetString("asjard.topology.services.example.name", "svc-example-api")).Conn()
	if err != nil {
		return err
	}
	api.client = NewConfigClient(conn)
	return nil
}
func (api *ConfigAPI) Stop() {
}

// Simple Get
// Retrieves the current configuration.
// Asjard generates both a gRPC method and a REST endpoint.
func (api *ConfigAPI) Get(ctx context.Context, in *ConfigGetReq) (*ConfigGetResp, error) {
	return api.client.Get(ctx, in)
}

// GetAndDecrypt: Retrieves an encrypted configuration and returns it in plain text.
// Demonstrates handling specialized business logic through the same framework.
func (api *ConfigAPI) GetAndDecrypt(ctx context.Context, in *common.Empty) (*ConfigDecryptResp, error) {
	return api.client.GetAndDecrypt(ctx, in)
}
func (api *ConfigAPI) RestServiceDesc() *rest.ServiceDesc {
	return &ConfigRestServiceDesc
}
