// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: protos-repo/example/api/v1/config.proto

// Package naming convention: api.{version}.{app}.{module}

package config

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "protos-repo/common/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Config_Get_FullMethodName           = "/api.v1.example.docs.Config/Get"
	Config_GetAndDecrypt_FullMethodName = "/api.v1.example.docs.Config/GetAndDecrypt"
)

// ConfigClient is the client API for Config service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigClient interface {
	// Simple Get: Retrieves the current configuration.
	// Asjard generates both a gRPC method and a REST endpoint.
	Get(ctx context.Context, in *ConfigGetReq, opts ...grpc.CallOption) (*ConfigGetResp, error)
	// GetAndDecrypt: Retrieves an encrypted configuration and returns it in plain text.
	// Demonstrates handling specialized business logic through the same framework.
	GetAndDecrypt(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*ConfigDecryptResp, error)
}

type configClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigClient(cc grpc.ClientConnInterface) ConfigClient {
	return &configClient{cc}
}

func (c *configClient) Get(ctx context.Context, in *ConfigGetReq, opts ...grpc.CallOption) (*ConfigGetResp, error) {
	out := new(ConfigGetResp)
	err := c.cc.Invoke(ctx, Config_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configClient) GetAndDecrypt(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*ConfigDecryptResp, error) {
	out := new(ConfigDecryptResp)
	err := c.cc.Invoke(ctx, Config_GetAndDecrypt_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServer is the server API for Config service.
// All implementations must embed UnimplementedConfigServer
// for forward compatibility
type ConfigServer interface {
	// Simple Get: Retrieves the current configuration.
	// Asjard generates both a gRPC method and a REST endpoint.
	Get(context.Context, *ConfigGetReq) (*ConfigGetResp, error)
	// GetAndDecrypt: Retrieves an encrypted configuration and returns it in plain text.
	// Demonstrates handling specialized business logic through the same framework.
	GetAndDecrypt(context.Context, *common.Empty) (*ConfigDecryptResp, error)
	mustEmbedUnimplementedConfigServer()
}

// UnimplementedConfigServer must be embedded to have forward compatible implementations.
type UnimplementedConfigServer struct {
}

func (UnimplementedConfigServer) Get(context.Context, *ConfigGetReq) (*ConfigGetResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedConfigServer) GetAndDecrypt(context.Context, *common.Empty) (*ConfigDecryptResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAndDecrypt not implemented")
}
func (UnimplementedConfigServer) mustEmbedUnimplementedConfigServer() {}

// UnsafeConfigServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServer will
// result in compilation errors.
type UnsafeConfigServer interface {
	mustEmbedUnimplementedConfigServer()
}

func RegisterConfigServer(s grpc.ServiceRegistrar, srv ConfigServer) {
	s.RegisterService(&Config_ServiceDesc, srv)
}

func _Config_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Config_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServer).Get(ctx, req.(*ConfigGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Config_GetAndDecrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServer).GetAndDecrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Config_GetAndDecrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServer).GetAndDecrypt(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Config_ServiceDesc is the grpc.ServiceDesc for Config service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Config_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.example.docs.Config",
	HandlerType: (*ConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Config_Get_Handler,
		},
		{
			MethodName: "GetAndDecrypt",
			Handler:    _Config_GetAndDecrypt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos-repo/example/api/v1/config.proto",
}
