// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: protos-repo/common/err_200_user.proto

package xcodes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ERR_USER int32

const (
	ERR_USER_EUSE_SUCCESS   ERR_USER = 0
	ERR_USER_EUSE_NOT_FOUND ERR_USER = 404201
	ERR_USER_EUSE_EXIST     ERR_USER = 409202
)

// Enum value maps for ERR_USER.
var (
	ERR_USER_name = map[int32]string{
		0:      "EUSE_SUCCESS",
		404201: "EUSE_NOT_FOUND",
		409202: "EUSE_EXIST",
	}
	ERR_USER_value = map[string]int32{
		"EUSE_SUCCESS":   0,
		"EUSE_NOT_FOUND": 404201,
		"EUSE_EXIST":     409202,
	}
)

func (x ERR_USER) Enum() *ERR_USER {
	p := new(ERR_USER)
	*p = x
	return p
}

func (x ERR_USER) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ERR_USER) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_repo_common_err_200_user_proto_enumTypes[0].Descriptor()
}

func (ERR_USER) Type() protoreflect.EnumType {
	return &file_protos_repo_common_err_200_user_proto_enumTypes[0]
}

func (x ERR_USER) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ERR_USER.Descriptor instead.
func (ERR_USER) EnumDescriptor() ([]byte, []int) {
	return file_protos_repo_common_err_200_user_proto_rawDescGZIP(), []int{0}
}

var File_protos_repo_common_err_200_user_proto protoreflect.FileDescriptor

var file_protos_repo_common_err_200_user_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x72, 0x65, 0x70, 0x6f, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x72, 0x72, 0x5f, 0x32, 0x30, 0x30, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x78, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x2a, 0x44, 0x0a, 0x08, 0x45, 0x52,
	0x52, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x55, 0x53, 0x45, 0x5f, 0x53,
	0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x0e, 0x45, 0x55, 0x53, 0x45,
	0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0xe9, 0xd5, 0x18, 0x12, 0x10,
	0x0a, 0x0a, 0x45, 0x55, 0x53, 0x45, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0xf2, 0xfc, 0x18,
	0x42, 0x1b, 0x5a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x72, 0x65, 0x70, 0x6f, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x78, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_repo_common_err_200_user_proto_rawDescOnce sync.Once
	file_protos_repo_common_err_200_user_proto_rawDescData = file_protos_repo_common_err_200_user_proto_rawDesc
)

func file_protos_repo_common_err_200_user_proto_rawDescGZIP() []byte {
	file_protos_repo_common_err_200_user_proto_rawDescOnce.Do(func() {
		file_protos_repo_common_err_200_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_repo_common_err_200_user_proto_rawDescData)
	})
	return file_protos_repo_common_err_200_user_proto_rawDescData
}

var file_protos_repo_common_err_200_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_repo_common_err_200_user_proto_goTypes = []interface{}{
	(ERR_USER)(0), // 0: api.common.xcodes.ERR_USER
}
var file_protos_repo_common_err_200_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_repo_common_err_200_user_proto_init() }
func file_protos_repo_common_err_200_user_proto_init() {
	if File_protos_repo_common_err_200_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_repo_common_err_200_user_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_repo_common_err_200_user_proto_goTypes,
		DependencyIndexes: file_protos_repo_common_err_200_user_proto_depIdxs,
		EnumInfos:         file_protos_repo_common_err_200_user_proto_enumTypes,
	}.Build()
	File_protos_repo_common_err_200_user_proto = out.File
	file_protos_repo_common_err_200_user_proto_rawDesc = nil
	file_protos_repo_common_err_200_user_proto_goTypes = nil
	file_protos_repo_common_err_200_user_proto_depIdxs = nil
}
