/*
 *
 * Copyright 2024 ASJARD authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package main

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/asjard/asjard/cmd/protoc-gen-go-amqp/utils"
	"github.com/asjard/asjard/pkg/protobuf/mqpb"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

const (
	contextPackage   = protogen.GoImportPath("context")
	configPakcage    = protogen.GoImportPath("github.com/asjard/asjard/core/config")
	xamqpPackage     = protogen.GoImportPath("github.com/asjard/asjard/pkg/server/xamqp")
	amqpStorePackage = protogen.GoImportPath("github.com/asjard/asjard/pkg/stores/amqp")
	jsonPackage      = protogen.GoImportPath("encoding/json")
	amqpPackage      = protogen.GoImportPath("github.com/streadway/amqp")
	serverPackage    = protogen.GoImportPath("github.com/asjard/asjard/core/server")
	protoPackage     = protogen.GoImportPath("google.golang.org/protobuf/proto")
	syncPackage      = protogen.GoImportPath("sync")
	bootstrapPackage = protogen.GoImportPath("github.com/asjard/asjard/core/bootstrap")
	// FileDescriptorProto.package field number
	fileDescriptorProtoPackageFieldNumber = 2
	// FileDescriptorProto.syntax field number
	fileDescriptorProtoSyntaxFieldNumber = 12
)

type amqpGenerator struct {
	plugin     *protogen.Plugin
	gen        *protogen.GeneratedFile
	file       *protogen.File
	openapiVar string
}

func NewAmqpGenerator(plugin *protogen.Plugin, file *protogen.File) *amqpGenerator {
	return &amqpGenerator{
		plugin:     plugin,
		file:       file,
		openapiVar: strings.ToLower(file.GoDescriptorIdent.GoName) + "_openapi",
	}
}

func (g *amqpGenerator) Run() *protogen.GeneratedFile {
	if len(g.file.Services) == 0 {
		return nil
	}
	g.gen = g.plugin.NewGeneratedFile(g.file.GeneratedFilenamePrefix+"_amqp.pb.go", g.file.GoImportPath)

	g.genLeadingComments(g.file.Desc.SourceLocations().ByPath(protoreflect.SourcePath{fileDescriptorProtoSyntaxFieldNumber}))
	g.gen.P("// Code generated by ", name, ". DO NOT EDIT.")
	g.gen.P("// versions:")
	g.gen.P("// - ", name, " v", version)
	g.gen.P("// - protoc             ", g.protocVersion())
	if g.file.Proto.GetOptions().GetDeprecated() {
		g.gen.P("// ", g.file.Desc.Path(), " is a deprecated file.")
	} else {
		g.gen.P("// source: ", g.file.Desc.Path())
	}
	g.gen.P()

	// Attach all comments associated with the package field.
	g.genLeadingComments(g.file.Desc.SourceLocations().ByPath(protoreflect.SourcePath{fileDescriptorProtoPackageFieldNumber}))
	g.gen.P("package ", g.file.GoPackageName)
	g.gen.P()

	g.genFileContent()
	return g.gen
}

func (g *amqpGenerator) genFileContent() {
	for _, service := range g.file.Services {
		g.genService(service)
	}
}

func (g *amqpGenerator) genService(service *protogen.Service) {
	handlerNames := make([]string, 0, len(service.Methods))
	serverType := service.GoName + "Server"
	clientType := service.GoName + "AmqpClient"
	g.genServiceClient(service, clientType)
	for _, method := range service.Methods {
		g.genServiceMethodClient(service, clientType, method)
	}
	for _, method := range service.Methods {
		hname := g.genServiceMethod(service, serverType, method)
		handlerNames = append(handlerNames, hname)
	}
	g.genServiceDesc(service, serverType, handlerNames)
}

//gocyclo:ignore
func (g *amqpGenerator) genServiceDesc(service *protogen.Service, serverType string, handlerNames []string) {
	serviceDescVar := service.GoName + "AmqpServiceDesc"
	// Service descriptor.
	g.gen.P("// ", serviceDescVar, " is the ", xamqpPackage.Ident("ServiceDesc"), " for ", service.GoName, " service.")
	g.gen.P("// It's only intended for direct use with ", xamqpPackage.Ident("AddHandler"), ",")
	g.gen.P("// and not to be introspected or modified (even as a copy)")
	g.genComment(service.Comments)
	g.gen.P("var ", serviceDescVar, " = ", xamqpPackage.Ident("ServiceDesc"), " {")
	g.gen.P("ServiceName: ", strconv.Quote(string(service.Desc.FullName())), ",")
	g.gen.P("HandlerType: (*", serverType, ")(nil),")
	g.gen.P("Methods: []", xamqpPackage.Ident("MethodDesc"), "{")
	for i, method := range service.Methods {
		if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
			continue
		}
		var methodDesc []byte
		commentLines := strings.Split(strings.TrimSuffix(method.Comments.Leading.String(), "\n"), "\n")
		commentLinesLen := len(commentLines)
		for index, line := range commentLines {
			methodDesc = append(methodDesc, strings.TrimPrefix(line, "// ")...)
			if index == commentLinesLen-1 {
				methodDesc = append(methodDesc, "."...)
			} else {
				methodDesc = append(methodDesc, ","...)
			}
		}
		mqOptions, ok := proto.GetExtension(method.Desc.Options(), mqpb.E_Mq).([]*mqpb.MQ)
		if ok {
			for _, mqOption := range mqOptions {
				g.gen.P("{")
				g.gen.P("Queue: ", fmt.Sprintf("%s_%s_FullMethodName", service.GoName, method.GoName), ",")
				g.gen.P("Handler: ", handlerNames[i], ",")
				option := utils.ParseMethodMqOption(service, mqOption)
				if option.Exchange != "" {
					g.gen.P("Exchange:", "\"", option.Exchange, "\",")
				}
				if option.Kind != "" {
					g.gen.P("Kind:", "\"", option.Kind, "\",")
				}
				if option.Route != "" {
					g.gen.P("Route:", "\"", option.Route, "\",")
				}
				if option.Consumer != "" {
					g.gen.P("Consumer:", "\"", option.Consumer, "\",")
				}
				if len(option.Table) != 0 {
					g.gen.P("Table:", "map[string]any{")
					for k, v := range option.Table {
						g.gen.P("\"", k, "\":", v, ",")
					}
					g.gen.P("},")

				}

				if option.AutoAck != nil {
					g.gen.P("AutoAck:", *option.AutoAck, ",")
				}
				if option.Durable != nil {
					g.gen.P("Durable:", *option.Durable, ",")
				}
				if option.AutoDelete != nil {
					g.gen.P("AutoDelete:", *option.AutoDelete, ",")
				}
				if option.Exclusive != nil {
					g.gen.P("Exclusive:", *option.Exclusive, ",")
				}
				if option.NoLocal != nil {
					g.gen.P("NoLocal:", *option.NoLocal, ",")
				}
				if option.NoWait != nil {
					g.gen.P("NoWait:", *option.NoWait, ",")
				}
				if option.Internal != nil {
					g.gen.P("NoWait:", *option.Internal, ",")
				}

				g.gen.P("},")
			}
		}

	}
	g.gen.P("},")
	g.gen.P("}")
	g.gen.P()
}

func (g *amqpGenerator) genServiceClient(service *protogen.Service, clientType string) {
	g.gen.P("type ", clientType, "Options struct {")
	g.gen.P("clientName string")
	g.gen.P("}")

	g.gen.P("type ", clientType, "Option func(opts *", clientType, "Options)")

	g.gen.P("func ", clientType, "WithClient(clientName string)", clientType, "Option{")
	g.gen.P("return func(opts *", clientType, "Options){")
	g.gen.P("if clientName != \"\"{")
	g.gen.P("opts.clientName=clientName")
	g.gen.P("}")
	g.gen.P("}")
	g.gen.P("}")

	g.gen.P("type ", clientType, " struct {")
	g.gen.P("*", amqpStorePackage.Ident("ClientConn"))
	g.gen.P("options *", clientType, "Options")
	g.gen.P("}")
	g.gen.P("")

	lowClientType := strings.ToLower(clientType[:1]) + clientType[1:]
	lowClientTypeOnce := lowClientType + "Once"
	g.gen.P("var (")
	g.gen.P(lowClientType, " *", clientType)
	g.gen.P(lowClientTypeOnce, " ", syncPackage.Ident("Once"))
	g.gen.P(")")

	g.gen.P("func New", clientType, "(opts ...", clientType, "Option", ")*", clientType, "{")
	g.gen.P(lowClientTypeOnce, ".Do(func() {")
	g.gen.P("options :=&", clientType, "Options{")
	g.gen.P("clientName:\"default\",")
	g.gen.P("}")

	g.gen.P("for _, opt := range opts {")
	g.gen.P("opt(options)")
	g.gen.P("}")

	g.gen.P(lowClientType, "=&", clientType, "{")
	g.gen.P("options:options,")
	g.gen.P("}")

	g.gen.P(bootstrapPackage.Ident("AddBootstrap"), "(", lowClientType, ")")
	g.gen.P("})")
	g.gen.P("return ", lowClientType)
	g.gen.P("}")

	g.gen.P("func(c *", clientType, ") Start() error {")
	g.gen.P("conn, err := ", amqpStorePackage.Ident("Client"), "(", amqpStorePackage.Ident("WithClientName"), "(c.options.clientName)", ")")
	g.gen.P("if err != nil {")
	g.gen.P("return err")
	g.gen.P("}")
	g.gen.P("c.ClientConn=conn")

	g.gen.P("ch, err := conn.Channel()")
	g.gen.P("if err != nil {")
	g.gen.P("return err")
	g.gen.P("}")

	g.gen.P("defer ch.Close()")

	g.gen.P("for _, method := range ", service.GoName+"AmqpServiceDesc.Methods{")

	g.gen.P("if method.Queue == \"\" {")
	g.gen.P("continue")
	g.gen.P("}")

	g.gen.P("if _, err := ch.QueueDeclare(method.Queue, method.Durable, method.AutoDelete, method.Exclusive, method.NoWait, method.Table); err != nil {")
	g.gen.P("return err")
	g.gen.P("}")

	g.gen.P("if method.Exchange != \"\" {")
	g.gen.P("if err := ch.ExchangeDeclare(method.Exchange,method.Kind, method.Durable, method.AutoDelete, method.Internal, method.NoWait, method.Table); err != nil {")
	g.gen.P("return err")
	g.gen.P("}")

	g.gen.P("if err := ch.QueueBind(method.Queue, method.Route, method.Exchange, method.NoWait, method.Table); err != nil {")
	g.gen.P("return err")
	g.gen.P("}")

	g.gen.P("}")
	g.gen.P("}")

	g.gen.P("return nil")
	g.gen.P("}")

	g.gen.P("func(c *", clientType, ") Stop() {}")

	g.gen.P("func(c *", clientType, ") GetChannel()(*", xamqpPackage.Ident("Channel"), ",error) {")
	g.gen.P("return c.ClientConn.Channel()")
	g.gen.P("}")
}

func (g *amqpGenerator) genServiceMethodClient(service *protogen.Service, clientType string, method *protogen.Method) {
	g.genComment(method.Comments)
	g.gen.P("func(c *", clientType, ")", method.GoName, "(ctx ", contextPackage.Ident("Context"), ",in *", method.Input.GoIdent, ",",
		"opts ...", xamqpPackage.Ident("PublishOption"), ")", "error{")
	g.gen.P("options := &", xamqpPackage.Ident("PublishOptions"), "{")
	g.gen.P("Key: ", fmt.Sprintf("%s_%s_FullMethodName", service.GoName, method.GoName), ",")
	g.gen.P("}")
	g.gen.P("for _, opt := range opts {")
	g.gen.P("opt(options)")
	g.gen.P("}")
	g.gen.P("payload, err := ", protoPackage.Ident("Marshal"), "(in)")
	g.gen.P("if err != nil {")
	g.gen.P("return err")
	g.gen.P("}")
	g.gen.P("ch, err := c.GetChannel()")
	g.gen.P("if err != nil {")
	g.gen.P("return err")
	g.gen.P("}")
	g.gen.P("defer ch.Close()")
	// c.Publish(exchange string, key string, mandatory bool, immediate bool, msg amqp.Publishing)
	g.gen.P("return ch.Publish(", `options.Exchange,`, "options.Key,", "options.Mandatory,", "options.Immediate,", amqpPackage.Ident("Publishing"), "{")
	g.gen.P("ContentType:\"application/protobuf\",")
	g.gen.P("Body:payload,")
	g.gen.P("})")
	g.gen.P("}")
}
func (g *amqpGenerator) genServiceMethod(service *protogen.Service, serverType string, method *protogen.Method) string {
	hname := fmt.Sprintf("_%s_%s_AmqpHandler", service.GoName, method.GoName)
	g.genComment(method.Comments)
	g.gen.P("func ", hname, "(ctx *", xamqpPackage.Ident("Context"), ", srv any, interceptor ", serverPackage.Ident("UnaryServerInterceptor"), ") (any, error) {")
	g.gen.P("in := new(", method.Input.GoIdent, ")")
	g.gen.P("if err := ", protoPackage.Ident("Unmarshal"), "(ctx.Body(), in); err != nil {")
	g.gen.P("return nil, err")
	g.gen.P("}")
	g.gen.P("if interceptor == nil {")
	g.gen.P("return srv.(", serverType, ").", method.GoName, "(ctx, in)")
	g.gen.P("}")
	g.gen.P("info := &", serverPackage.Ident("UnaryServerInfo"), "{")
	g.gen.P("Server: srv,")
	g.gen.P("FullMethod: ", fmt.Sprintf("%s_%s_FullMethodName,", service.GoName, method.GoName))
	g.gen.P("Protocol: ", xamqpPackage.Ident("Protocol"), ",")
	g.gen.P("}")
	g.gen.P("handler := func(ctx ", contextPackage.Ident("Context"), ",req any)(any, error) {")
	g.gen.P("return srv.(", serverType, ").", method.GoName, "(ctx, in)")
	g.gen.P("}")
	g.gen.P("return interceptor(ctx, in, info, handler)")
	g.gen.P("}")
	return hname
}

func (g *amqpGenerator) genLeadingComments(loc protoreflect.SourceLocation) {
	for _, s := range loc.LeadingDetachedComments {
		g.gen.P(protogen.Comments(s))
		g.gen.P()
	}
	if s := loc.LeadingComments; s != "" {
		g.gen.P(protogen.Comments(s))
		g.gen.P()
	}
}

func (g *amqpGenerator) genComment(comments protogen.CommentSet) {
	if comments.Leading != "" {
		g.gen.P("//")
		g.gen.P(strings.TrimSpace(comments.Leading.String()))
	}
}

func (g *amqpGenerator) protocVersion() string {
	v := g.plugin.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}
