// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: rest_default.proto

package rest

import (
	_ "github.com/asjard/asjard/pkg/protobuf/httppb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Route info
type RouteInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routes []*RouteInfo_Node `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
}

func (x *RouteInfo) Reset() {
	*x = RouteInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rest_default_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteInfo) ProtoMessage() {}

func (x *RouteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rest_default_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteInfo.ProtoReflect.Descriptor instead.
func (*RouteInfo) Descriptor() ([]byte, []int) {
	return file_rest_default_proto_rawDescGZIP(), []int{0}
}

func (x *RouteInfo) GetRoutes() []*RouteInfo_Node {
	if x != nil {
		return x.Routes
	}
	return nil
}

type RouteInfo_Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label    string            `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value    string            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Children []*RouteInfo_Node `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *RouteInfo_Node) Reset() {
	*x = RouteInfo_Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rest_default_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteInfo_Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteInfo_Node) ProtoMessage() {}

func (x *RouteInfo_Node) ProtoReflect() protoreflect.Message {
	mi := &file_rest_default_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteInfo_Node.ProtoReflect.Descriptor instead.
func (*RouteInfo_Node) Descriptor() ([]byte, []int) {
	return file_rest_default_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RouteInfo_Node) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *RouteInfo_Node) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RouteInfo_Node) GetChildren() []*RouteInfo_Node {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_rest_default_proto protoreflect.FileDescriptor

var file_rest_default_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x65, 0x73, 0x74, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x73, 0x6a, 0x61, 0x72, 0x64, 0x2e, 0x61, 0x70, 0x69,
	0x1a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x73, 0x6a,
	0x61, 0x72, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x68, 0x74, 0x74,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab, 0x01, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x32, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x73, 0x6a, 0x61, 0x72, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x06,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x1a, 0x6a, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61,
	0x73, 0x6a, 0x61, 0x72, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72,
	0x65, 0x6e, 0x32, 0x6b, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x06, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x61, 0x73, 0x6a,
	0x61, 0x72, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x0d, 0x82, 0xb5, 0x18, 0x09, 0x12, 0x07, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73,
	0x1a, 0x0d, 0x82, 0xa6, 0x1d, 0x09, 0x4a, 0x01, 0x2f, 0x52, 0x01, 0x2f, 0x5a, 0x01, 0x2f, 0x42,
	0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x73,
	0x6a, 0x61, 0x72, 0x64, 0x2f, 0x61, 0x73, 0x6a, 0x61, 0x72, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_rest_default_proto_rawDescOnce sync.Once
	file_rest_default_proto_rawDescData = file_rest_default_proto_rawDesc
)

func file_rest_default_proto_rawDescGZIP() []byte {
	file_rest_default_proto_rawDescOnce.Do(func() {
		file_rest_default_proto_rawDescData = protoimpl.X.CompressGZIP(file_rest_default_proto_rawDescData)
	})
	return file_rest_default_proto_rawDescData
}

var file_rest_default_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rest_default_proto_goTypes = []interface{}{
	(*RouteInfo)(nil),      // 0: asjard.api.RouteInfo
	(*RouteInfo_Node)(nil), // 1: asjard.api.RouteInfo.Node
	(*emptypb.Empty)(nil),  // 2: google.protobuf.Empty
}
var file_rest_default_proto_depIdxs = []int32{
	1, // 0: asjard.api.RouteInfo.routes:type_name -> asjard.api.RouteInfo.Node
	1, // 1: asjard.api.RouteInfo.Node.children:type_name -> asjard.api.RouteInfo.Node
	2, // 2: asjard.api.RestDefaultHandler.Routes:input_type -> google.protobuf.Empty
	0, // 3: asjard.api.RestDefaultHandler.Routes:output_type -> asjard.api.RouteInfo
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rest_default_proto_init() }
func file_rest_default_proto_init() {
	if File_rest_default_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rest_default_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rest_default_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteInfo_Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rest_default_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rest_default_proto_goTypes,
		DependencyIndexes: file_rest_default_proto_depIdxs,
		MessageInfos:      file_rest_default_proto_msgTypes,
	}.Build()
	File_rest_default_proto = out.File
	file_rest_default_proto_rawDesc = nil
	file_rest_default_proto_goTypes = nil
	file_rest_default_proto_depIdxs = nil
}
