// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: rest_default.proto

package rest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RestDefaultHandler_Routes_FullMethodName = "/asjard.api.RestDefaultHandler/Routes"
)

// RestDefaultHandlerClient is the client API for RestDefaultHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestDefaultHandlerClient interface {
	// Return route list
	Routes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RouteInfo, error)
}

type restDefaultHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewRestDefaultHandlerClient(cc grpc.ClientConnInterface) RestDefaultHandlerClient {
	return &restDefaultHandlerClient{cc}
}

func (c *restDefaultHandlerClient) Routes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RouteInfo, error) {
	out := new(RouteInfo)
	err := c.cc.Invoke(ctx, RestDefaultHandler_Routes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestDefaultHandlerServer is the server API for RestDefaultHandler service.
// All implementations must embed UnimplementedRestDefaultHandlerServer
// for forward compatibility
type RestDefaultHandlerServer interface {
	// Return route list
	Routes(context.Context, *emptypb.Empty) (*RouteInfo, error)
	mustEmbedUnimplementedRestDefaultHandlerServer()
}

// UnimplementedRestDefaultHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedRestDefaultHandlerServer struct {
}

func (UnimplementedRestDefaultHandlerServer) Routes(context.Context, *emptypb.Empty) (*RouteInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Routes not implemented")
}
func (UnimplementedRestDefaultHandlerServer) mustEmbedUnimplementedRestDefaultHandlerServer() {}

// UnsafeRestDefaultHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestDefaultHandlerServer will
// result in compilation errors.
type UnsafeRestDefaultHandlerServer interface {
	mustEmbedUnimplementedRestDefaultHandlerServer()
}

func RegisterRestDefaultHandlerServer(s grpc.ServiceRegistrar, srv RestDefaultHandlerServer) {
	s.RegisterService(&RestDefaultHandler_ServiceDesc, srv)
}

func _RestDefaultHandler_Routes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestDefaultHandlerServer).Routes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestDefaultHandler_Routes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestDefaultHandlerServer).Routes(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RestDefaultHandler_ServiceDesc is the grpc.ServiceDesc for RestDefaultHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestDefaultHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asjard.api.RestDefaultHandler",
	HandlerType: (*RestDefaultHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Routes",
			Handler:    _RestDefaultHandler_Routes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rest_default.proto",
}
