asjard:
  ## config management
  config:
    ## Adding a default configuration source
    ## The Set method sets the default configuration source. If not specified or empty, all configuration sources are sent. Defaults to mem
    ## Whether you can add a configuration source depends on whether the specific configuration source implements the Set function.
    # setDefaultSource: mem

    ## etcd configuration source
    etcd:
      ## etcd client name
      ## asjard.stores.etcd.clients.{this name}
      # client: default
      ## key split delimiter
      # delimiter: "/"
    ## consul configuration source
    consul:
      ## consul client name
      ## asjard.stores.consul.clients.{this name}
      # client: default
      ## key split delimiter
      # delimiter: "/"
