asjard:
  ## 配置中心相关
  config:
    ## 添加配置默认配置源
    ## Set方法默认配置源, 如果不配置或者为空，则发送给所有配置源
    setDefaultSource: mem
    ## etcd配置中心配置
    etcd:
      ## 配置中心地址
      endpoints: []
      ## - {{database.etcd.endpoints[0]}}
      ## - {{database.etcd.endpoints[1]}}
      options:
        x: y
