// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: validate.proto

package validatepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 参数校验
type Validate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 校验规则
	// 参考: https://github.com/go-playground/validator?tab=readme-ov-file
	// 由于不同的方法有可能会使用同一个message，因此在此基础上扩展不同方法自定义规则
	//
	// 格式: [method_name:]<rule>;...;[method_name_N:]<rule_N>
	// 方法名和规则之间用冒号分隔, 多个规则之间用分号分隔
	//
	// 例如:
	// max=10;Create:required;Update:min=1
	// 全局校验: max=10
	// Create方法在全局方法基础上额外添加: required, 最终: max=10,required
	// Update方法在全局方法基础上额外添加: min=1, 最终: max=10,min=1
	Rules string `protobuf:"bytes,1,opt,name=rules,proto3" json:"rules,omitempty"`
	// 错误码
	ErrCode uint32 `protobuf:"varint,2,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
}

func (x *Validate) Reset() {
	*x = Validate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_validate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Validate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validate) ProtoMessage() {}

func (x *Validate) ProtoReflect() protoreflect.Message {
	mi := &file_validate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validate.ProtoReflect.Descriptor instead.
func (*Validate) Descriptor() ([]byte, []int) {
	return file_validate_proto_rawDescGZIP(), []int{0}
}

func (x *Validate) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

func (x *Validate) GetErrCode() uint32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

var file_validate_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Validate)(nil),
		Field:         70000,
		Name:          "asjard.api.validate",
		Tag:           "bytes,70000,opt,name=validate",
		Filename:      "validate.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional asjard.api.Validate validate = 70000;
	E_Validate = &file_validate_proto_extTypes[0]
)

var File_validate_proto protoreflect.FileDescriptor

var file_validate_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x61, 0x73, 0x6a, 0x61, 0x72, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x20, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b,
	0x0a, 0x08, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x75,
	0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73,
	0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x3a, 0x51, 0x0a, 0x08, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xf0, 0xa2, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x61, 0x73, 0x6a, 0x61, 0x72, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x08, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x42, 0x3d,
	0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x73, 0x6a,
	0x61, 0x72, 0x64, 0x2f, 0x61, 0x73, 0x6a, 0x61, 0x72, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x70, 0x62, 0x3b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_validate_proto_rawDescOnce sync.Once
	file_validate_proto_rawDescData = file_validate_proto_rawDesc
)

func file_validate_proto_rawDescGZIP() []byte {
	file_validate_proto_rawDescOnce.Do(func() {
		file_validate_proto_rawDescData = protoimpl.X.CompressGZIP(file_validate_proto_rawDescData)
	})
	return file_validate_proto_rawDescData
}

var file_validate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_validate_proto_goTypes = []interface{}{
	(*Validate)(nil),                  // 0: asjard.api.Validate
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_validate_proto_depIdxs = []int32{
	1, // 0: asjard.api.validate:extendee -> google.protobuf.FieldOptions
	0, // 1: asjard.api.validate:type_name -> asjard.api.Validate
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_validate_proto_init() }
func file_validate_proto_init() {
	if File_validate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_validate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Validate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_validate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_validate_proto_goTypes,
		DependencyIndexes: file_validate_proto_depIdxs,
		MessageInfos:      file_validate_proto_msgTypes,
		ExtensionInfos:    file_validate_proto_extTypes,
	}.Build()
	File_validate_proto = out.File
	file_validate_proto_rawDesc = nil
	file_validate_proto_goTypes = nil
	file_validate_proto_depIdxs = nil
}
