// Code generated by protoc-gen-ts. DO NOT EDIT.
// versions:
// - protoc-gen-ts v1.3.0
// - protoc             v5.27.0
// source: file.proto

interface UploadReq{
    file: string;
}

interface UploadResp{
    download_name: string;
}

interface DownloadReq{
    file_name: string;
}

