// Code generated by protoc-gen-ts. DO NOT EDIT.
// versions:
// - protoc-gen-ts v1.3.0
// - protoc             v5.27.0
// source: file.proto



// -----------
export interface UploadReq{
//file:string
    file: string;
}
// -----------
export interface UploadResp{
//download_name:string
    download_name: string;
}
// -----------
export interface DownloadReq{
//file_name:string
    file_name: string;
}
