// Code generated by protoc-gen-go-amqp. DO NOT EDIT.
// versions:
// - protoc-gen-go-amqp v1.0.0
// - protoc             v5.27.0
// source: protos-repo/example/api/v1/hello.proto

// 约定此处格式为: {接口类型}.{接口版本}.{服务名称}[.服务分类]
// 其中{接口类型},{接口版本},[服务分类]会在rest服务中用来生成路由前缀
// 可在ajard.api.http中通过api,和version字段修改
// 例如如下package名称生成的路由前缀为/api/v1/docs
//
// {服务名称}会在生成gw代码时用以确定客户端名称, 例如:
// conn, err := client.NewClient(grpc.Protocol, config.GetString("asjard.topology.services.{hello}.name", "{hello}")).Conn()
// 如果修改了asjard.service.instance.name 则可以通过asjard.topology.service.hello.name修改

package hello

import (
	context "context"
	bootstrap "github.com/asjard/asjard/core/bootstrap"
	server "github.com/asjard/asjard/core/server"
	xamqp1 "github.com/asjard/asjard/pkg/server/xamqp"
	xamqp "github.com/asjard/asjard/pkg/stores/xamqp"
	amqp "github.com/streadway/amqp"
	proto "google.golang.org/protobuf/proto"
	sync "sync"
)

type HelloAmqpClientOptions struct {
	clientName string
}
type HelloAmqpClientOption func(opts *HelloAmqpClientOptions)

func HelloAmqpClientWithClient(clientName string) HelloAmqpClientOption {
	return func(opts *HelloAmqpClientOptions) {
		if clientName != "" {
			opts.clientName = clientName
		}
	}
}

type HelloAmqpClient struct {
	*xamqp.ClientConn
	options *HelloAmqpClientOptions
}

var (
	helloAmqpClient     *HelloAmqpClient
	helloAmqpClientOnce sync.Once
)

func NewHelloAmqpClient(opts ...HelloAmqpClientOption) *HelloAmqpClient {
	helloAmqpClientOnce.Do(func() {
		options := &HelloAmqpClientOptions{
			clientName: "default",
		}
		for _, opt := range opts {
			opt(options)
		}
		helloAmqpClient = &HelloAmqpClient{
			options: options,
		}
		bootstrap.AddBootstrap(helloAmqpClient)
	})
	return helloAmqpClient
}
func (c *HelloAmqpClient) Start() error {
	conn, err := xamqp.Client(xamqp.WithClientName(c.options.clientName))
	if err != nil {
		return err
	}
	c.ClientConn = conn
	ch, err := conn.Channel()
	if err != nil {
		return err
	}
	defer ch.Close()
	for _, method := range HelloAmqpServiceDesc.Methods {
		if method.Queue != "" {
			if _, err := ch.QueueDeclare(method.Queue, method.Durable, method.AutoDelete, method.Exclusive, method.NoWait, method.Table); err != nil {
				return err
			}
		}
		if method.Exchange != "" {
			if err := ch.ExchangeDeclare(method.Exchange, method.Kind, method.Durable, method.AutoDelete, method.Internal, method.NoWait, method.Table); err != nil {
				return err
			}
			if method.Queue != "" {
				if err := ch.QueueBind(method.Queue, method.Route, method.Exchange, method.NoWait, method.Table); err != nil {
					return err
				}
			}
		}
	}
	return nil
}
func (c *HelloAmqpClient) Stop() {}
func (c *HelloAmqpClient) GetChannel() (*amqp.Channel, error) {
	return c.ClientConn.Channel()
}

// 可以对整个服务定义路由信息
// option(asjard.api.serviceHttp) = {api: "api", versin: "v1", group:"hello", writer_name: "custome_writer"}
// 功能描述,
// 支持markdown
// 可渲染在openapi文档的接口描述中
// 渲染在rest服务的路由描述中
func (c *HelloAmqpClient) Say(ctx context.Context, in *SayReq, opts ...xamqp1.PublishOption) error {
	options := &xamqp1.PublishOptions{}
	for _, opt := range opts {
		opt(options)
	}
	payload, err := proto.Marshal(in)
	if err != nil {
		return err
	}
	ch, err := c.GetChannel()
	if err != nil {
		return err
	}
	defer ch.Close()
	return ch.Publish(options.Exchange, options.Key, options.Mandatory, options.Immediate, amqp.Publishing{
		ContentType: "application/protobuf",
		Body:        payload,
	})
}

// 可以对整个服务定义路由信息
// option(asjard.api.serviceHttp) = {api: "api", versin: "v1", group:"hello", writer_name: "custome_writer"}
// 功能描述,
// 支持markdown
// 可渲染在openapi文档的接口描述中
// 渲染在rest服务的路由描述中
func _Hello_Say_AmqpHandler(ctx *xamqp1.Context, srv any, interceptor server.UnaryServerInterceptor) (any, error) {
	in := new(SayReq)
	if err := proto.Unmarshal(ctx.Body(), in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).Say(ctx, in)
	}
	info := &server.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hello_Say_FullMethodName,
		Protocol:   xamqp1.Protocol,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(HelloServer).Say(ctx, in)
	}
	return interceptor(ctx, in, info, handler)
}

// HelloAmqpServiceDesc is the xamqp1.ServiceDesc for Hello service.
// It's only intended for direct use with xamqp1.AddHandler,
// and not to be introspected or modified (even as a copy)
//
// 需要实现的功能
// 一个proto文件中只写一个service
// 如果在rest中没有配置group字段，则service名称为group字段的值
var HelloAmqpServiceDesc = xamqp1.ServiceDesc{
	ServiceName: "api.v1.example.docs.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []xamqp1.MethodDesc{
		{
			Queue:   Hello_Say_FullMethodName,
			Handler: _Hello_Say_AmqpHandler,
		},
	},
}
