// Code generated by protoc-gen-go-rest2grpc-gw. DO NOT EDIT.
// versions:
// - protoc-gen-go-rest2grpc-gw v1.3.0
// - protoc             v5.27.0
// source: protos-repo/example/api/v1/hello.proto

// 约定此处格式为: {接口类型}.{接口版本}.{服务名称}[.服务分类]
// 其中{接口类型},{接口版本},[服务分类]会在rest服务中用来生成路由前缀
// 可在ajard.api.http中通过api,和version字段修改
// 例如如下package名称生成的路由前缀为/api/v1/docs
//
// {服务名称}会在生成gw代码时用以确定客户端名称, 例如:
// conn, err := client.NewClient(grpc.Protocol, config.GetString("asjard.topology.services.{hello}.name", "{hello}")).Conn()
// 如果修改了asjard.service.instance.name 则可以通过asjard.topology.service.hello.name修改

package hello

import (
	context "context"
	bootstrap "github.com/asjard/asjard/core/bootstrap"
	client "github.com/asjard/asjard/core/client"
	config "github.com/asjard/asjard/core/config"
	grpc "github.com/asjard/asjard/pkg/client/grpc"
	rest "github.com/asjard/asjard/pkg/server/rest"
	sync "sync"
)

type HelloAPI struct {
	UnimplementedHelloServer
	client HelloClient
}

var (
	helloAPI     *HelloAPI
	helloAPIOnce sync.Once
)

func NewHelloAPI() *HelloAPI {
	helloAPIOnce.Do(func() {
		helloAPI = &HelloAPI{}
		bootstrap.AddBootstrap(helloAPI)
	})
	return helloAPI
}
func (api *HelloAPI) Start() error {
	conn, err := client.NewClient(grpc.Protocol, config.GetString("asjard.topology.services.example.name", "svc-example-api")).Conn()
	if err != nil {
		return err
	}
	api.client = NewHelloClient(conn)
	return nil
}
func (api *HelloAPI) Stop() {
}

// 可以对整个服务定义路由信息
// option(asjard.api.serviceHttp) = {api: "api", versin: "v1", group:"hello", writer_name: "custome_writer"}
// 功能描述,
// 支持markdown
// 可渲染在openapi文档的接口描述中
// 渲染在rest服务的路由描述中
func (api *HelloAPI) Say(ctx context.Context, in *SayReq) (*SayResp, error) {
	return api.client.Say(ctx, in)
}
func (api *HelloAPI) RestServiceDesc() *rest.ServiceDesc {
	return &HelloRestServiceDesc
}
