// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// versions:
// - protoc-gen-go-validate v1.0.1
// - protoc             v5.27.0
// source: protos-repo/example/api/v1/hello.proto

// 约定此处格式为: {接口类型}.{接口版本}.{服务名称}[.服务分类]
// 其中{接口类型},{接口版本},[服务分类]会在rest服务中用来生成路由前缀
// 可在ajard.api.http中通过api,和version字段修改
// 例如如下package名称生成的路由前缀为/api/v1/docs
//
// {服务名称}会在生成gw代码时用以确定客户端名称, 例如:
// conn, err := client.NewClient(grpc.Protocol, config.GetString("asjard.topology.services.{hello}.name", "{hello}")).Conn()
// 如果修改了asjard.service.instance.name 则可以通过asjard.topology.service.hello.name修改

package hello

import (
	status "github.com/asjard/asjard/core/status"
	validatepb "github.com/asjard/asjard/pkg/protobuf/validatepb"
	codes "google.golang.org/grpc/codes"
)

// IsValid Params validate
// 请求参数
func (m *SayReq) IsValid(parentFieldName, fullMethod string) error {
	v := validatepb.DefaultValidator
	if err := v.Var(m.Name, "required,max=20"); err != nil {
		return status.Errorf(codes.InvalidArgument, "validation field '%s' on 'required,max=20' fail", validatepb.ValidateFieldName(parentFieldName, "name"))
	}
	return nil
}

// IsValid Params validate
// 请求返回
func (m *SayResp) IsValid(parentFieldName, fullMethod string) error {
	return nil
}
