package handlers

import (
	"context"
	"path/filepath"

	"github.com/asjard/asjard/core/runtime"
	"github.com/asjard/asjard/core/server/handlers"
	"github.com/asjard/asjard/pkg/protobuf/requestpb"
	"github.com/asjard/asjard/pkg/server/rest"
	"github.com/asjard/asjard/utils"
	"github.com/valyala/fasthttp"
	"google.golang.org/protobuf/types/known/emptypb"
)

// DefaultHandlersAPI provides the implementation for system-level default endpoints.
// It embeds the Unimplemented server to ensure forward compatibility with Protobuf changes.
type DefaultHandlersAPI struct {
	requestpb.UnimplementedDefaultHandlersServer
}

func init() {
	// Automatically register these default handlers when the package is imported.
	// This makes them available specifically under the "rest" protocol.
	handlers.AddServerDefaultHandler("default", &DefaultHandlersAPI{}, rest.Protocol)
}

// Favicon handles requests for the browser's shortcut icon (usually /favicon.ico).
// It looks for the icon file defined in the application's runtime configuration.
func (api *DefaultHandlersAPI) Favicon(ctx context.Context, in *emptypb.Empty) (*emptypb.Empty, error) {
	// Type assertion to access the specific REST context (fasthttp wrapper).
	rtx, ok := ctx.(*rest.Context)
	if ok {
		// Resolve the absolute path to the favicon file based on the application's home directory.
		faviconFile := filepath.Join(utils.GetHomeDir(), runtime.GetAPP().Favicon)

		// If the file exists on disk, set the correct Content-Type and stream the file.
		if utils.IsPathExists(faviconFile) {
			rtx.Response.Header.Set(fasthttp.HeaderContentType, "image/x-icon")
			rtx.SendFile(faviconFile)
			// Returning nil, nil prevents the standard gRPC response from being sent.
			return nil, nil
		}
	}
	// Return an empty response if the context is invalid or the file is not found.
	return &emptypb.Empty{}, nil
}

// RestServiceDesc returns the RESTful service description generated by the protobuf compiler.
// This allows the framework to map HTTP routes to these gRPC methods.
func (api *DefaultHandlersAPI) RestServiceDesc() *rest.ServiceDesc {
	return &requestpb.DefaultHandlersRestServiceDesc
}
