// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// versions:
// - protoc-gen-go-validate v1.0.1
// - protoc             v5.27.0
// source: protos-repo/example/api/v1/sample.proto

package sample

import (
	status "github.com/asjard/asjard/core/status"
	validatepb "github.com/asjard/asjard/pkg/protobuf/validatepb"
	codes "google.golang.org/grpc/codes"
)

// IsValid Params validate
// HelloRequest defines the input payload for the SayHello method.
func (m *HelloRequest) IsValid(parentFieldName, fullMethod string) error {
	v := validatepb.DefaultValidator
	if err := v.Var(m.Name, "required,max=20"); err != nil {
		return status.Errorf(codes.InvalidArgument, "validation field '%s' on 'required,max=20' fail", validatepb.ValidateFieldName(parentFieldName, "name"))
	}
	return nil
}

// IsValid Params validate
// HelloReply defines the output payload containing the greeting result.
func (m *HelloReply) IsValid(parentFieldName, fullMethod string) error {
	return nil
}
