// Code generated by protoc-gen-go-amqp. DO NOT EDIT.
// versions:
// - protoc-gen-go-amqp v1.0.0
// - protoc             v5.27.0
// source: protos-repo/example/api/v1/sample.proto

package sample

import (
	bootstrap "github.com/asjard/asjard/core/bootstrap"
	xamqp1 "github.com/asjard/asjard/pkg/server/xamqp"
	xamqp "github.com/asjard/asjard/pkg/stores/xamqp"
	amqp091_go "github.com/rabbitmq/amqp091-go"
	sync "sync"
)

type SampleAmqpClientOptions struct {
	clientName string
}
type SampleAmqpClientOption func(opts *SampleAmqpClientOptions)

func SampleAmqpClientWithClient(clientName string) SampleAmqpClientOption {
	return func(opts *SampleAmqpClientOptions) {
		if clientName != "" {
			opts.clientName = clientName
		}
	}
}

type SampleAmqpClient struct {
	*xamqp.ClientConn
	options *SampleAmqpClientOptions
}

var (
	sampleAmqpClient     *SampleAmqpClient
	sampleAmqpClientOnce sync.Once
)

func NewSampleAmqpClient(opts ...SampleAmqpClientOption) *SampleAmqpClient {
	sampleAmqpClientOnce.Do(func() {
		options := &SampleAmqpClientOptions{
			clientName: "default",
		}
		for _, opt := range opts {
			opt(options)
		}
		sampleAmqpClient = &SampleAmqpClient{
			options: options,
		}
		bootstrap.AddBootstrap(sampleAmqpClient)
	})
	return sampleAmqpClient
}
func (c *SampleAmqpClient) Start() error {
	conn, err := xamqp.Client(xamqp.WithClientName(c.options.clientName))
	if err != nil {
		return err
	}
	c.ClientConn = conn
	ch, err := conn.Channel()
	if err != nil {
		return err
	}
	defer ch.Close()
	for _, method := range SampleAmqpServiceDesc.Methods {
		if method.Queue != "" {
			if _, err := ch.QueueDeclare(method.Queue, method.Durable, method.AutoDelete, method.Exclusive, method.NoWait, method.Table); err != nil {
				return err
			}
		}
		if method.Exchange != "" {
			if err := ch.ExchangeDeclare(method.Exchange, method.Kind, method.Durable, method.AutoDelete, method.Internal, method.NoWait, method.Table); err != nil {
				return err
			}
			if method.Queue != "" {
				if err := ch.QueueBind(method.Queue, method.Route, method.Exchange, method.NoWait, method.Table); err != nil {
					return err
				}
			}
		}
	}
	return nil
}
func (c *SampleAmqpClient) Stop() {}
func (c *SampleAmqpClient) GetChannel() (*amqp091_go.Channel, error) {
	return c.ClientConn.Channel()
}

const ()

// SampleAmqpServiceDesc is the xamqp1.ServiceDesc for Sample service.
// It's only intended for direct use with xamqp1.AddHandler,
// and not to be introspected or modified (even as a copy)
//
// Sample service provides basic greeting operations.
var SampleAmqpServiceDesc = xamqp1.ServiceDesc{
	ServiceName: "api.v1.example.docs.Sample",
	HandlerType: (*SampleServer)(nil),
	Methods:     []xamqp1.MethodDesc{},
}
