// Code generated by protoc-gen-go-rest2grpc-gw. DO NOT EDIT.
// versions:
// - protoc-gen-go-rest2grpc-gw v1.3.0
// - protoc             v5.27.0
// source: protos-repo/example/api/v1/sample.proto

package sample

import (
	context "context"
	bootstrap "github.com/asjard/asjard/core/bootstrap"
	client "github.com/asjard/asjard/core/client"
	config "github.com/asjard/asjard/core/config"
	grpc "github.com/asjard/asjard/pkg/client/grpc"
	rest "github.com/asjard/asjard/pkg/server/rest"
	sync "sync"
)

type SampleAPI struct {
	UnimplementedSampleServer
	client SampleClient
}

var (
	sampleAPI     *SampleAPI
	sampleAPIOnce sync.Once
)

func NewSampleAPI() *SampleAPI {
	sampleAPIOnce.Do(func() {
		sampleAPI = &SampleAPI{}
		bootstrap.AddBootstrap(sampleAPI)
	})
	return sampleAPI
}
func (api *SampleAPI) Start() error {
	conn, err := client.NewClient(grpc.Protocol, config.GetString("asjard.topology.services.example.name", "svc-example-api")).Conn()
	if err != nil {
		return err
	}
	api.client = NewSampleClient(conn)
	return nil
}
func (api *SampleAPI) Stop() {
}
func (api *SampleAPI) SayHello(ctx context.Context, in *HelloRequest) (*HelloReply, error) {
	return api.client.SayHello(ctx, in)
}
func (api *SampleAPI) RestServiceDesc() *rest.ServiceDesc {
	return &SampleRestServiceDesc
}
