{
 "title": "ASJARD",
 "tags": [
  "Go ",
  "RPC",
  "HTTP",
  "Microservice",
  "Asjard"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "app", "query": { "query": "label_values(go_info,job)" } },
   {
    "name": "region",
    "query": {
     "query": "label_values({app=\"$app\"},region)"
    }
   },
   {
    "name": "az",
    "query": {
     "query": "label_values({app=\"$app\", region=\"$region\"},az)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(go_info{job=\"$app\"},service)"
    }
   },
   { "name": "env", "query": { "query": "label_values(env)" } },
   {
    "name": "api",
    "query": {
     "query": "label_values(api_requests_total{job=\"$app\", service=\"$service\"},api)"
    }
   },
   {
    "name": "protocol",
    "query": {
     "query": "label_values(api_requests_total{job=\"$app\"},protocol)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(go_info{job=\"$app\", service=~\"$service\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Rate (no internal server error responses)",
   "type": "gauge",
   "description": "No internval server error responses divided by all responses as reported",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service)(irate(api_requests_total{app=\"$app\",code!~\"12|13|14\",  service=~\"$service\",region=~\"$region\", az=~\"$az\", env=~\"$env\", api=~\"$api\", protocol=~\"$protocol\", instance=~\"$instance\"}[$__rate_interval])) / sum by (service)(irate(api_requests_total{app=\"$app\", service=~\"$service\",region=~\"$region\", az=~\"$az\", env=~\"$env\", api=~\"$api\", protocol=~\"$protocol\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Reqs (2m)",
   "type": "stat",
   "description": "The number of HTTP requests made in the last 2 minute window",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_requests_total{ app=\"$app\", service=~\"$service\", env=~\"$env\", api=~\"$api\", protocol=~\"$protocol\", instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Success (2m)",
   "type": "stat",
   "description": "This is the percentage of successful requests over the last minute.\n\nNOTE: Ignoring 404s in this metric, since a  404 is a normal response for errant requests",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_requests_total{app=\"$app\", service=~\"$service\",region=~\"$region\", az=~\"$az\", env=~\"$env\", api=~\"$api\", protocol=~\"$protocol\", instance=~\"$instance\"}[$__interval])) / \n(sum(rate(api_requests_total{app=\"$app\", service=~\"$service\",region=~\"$region\", az=~\"$az\", env=~\"$env\", api=~\"$api\", protocol=~\"$protocol\", instance=~\"$instance\"}[$__interval])) - \n(sum(rate(api_requests_total{app=\"$app\", code!=\"0\", service=~\"$service\",region=~\"$region\", az=~\"$az\", env=~\"$env\", api=~\"$api\", protocol=~\"$protocol\", instance=~\"$instance\"}[$__interval])) or vector(0)))"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "stat",
   "description": "Green if < 50ms, Yellow if < 100ms, Red if > 100ms",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_requests_latency_ms{app=\"$app\",instance=~\"$instance\",service=~\"$service\",region=~\"$region\", az=~\"$az\",api=~\"$api\", protocol=~\"$protocol\", quantile=\"0.5\"}",
     "legendFormat": "P50"
    },
    {
     "expr": "api_requests_latency_ms{app=\"$app\",instance=~\"$instance\",service=~\"$service\",region=~\"$region\", az=~\"$az\",api=~\"$api\", protocol=~\"$protocol\", quantile=\"0.9\"}",
     "legendFormat": "P90"
    },
    {
     "expr": "api_requests_latency_ms{app=\"$app\",instance=~\"$instance\",service=~\"$service\",region=~\"$region\", az=~\"$az\",api=~\"$api\", protocol=~\"$protocol\", quantile=\"0.99\"}",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Requests (period)",
   "type": "stat",
   "description": "This is the total number of requests made in this period (top-right period selected)",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_requests_total{ app=\"$app\", service=~\"$service\", env=~\"$env\", api=~\"$api\", protocol=~\"$protocol\", instance=~\"$instance\"}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Requests / Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (api,protocol) (rate(api_requests_total{app=\"$app\", service=~\"$service\", env=~\"$env\", api=~\"$api\", instance=~\"$instance\",protocol=~\"$protocol\"}[5m]))",
     "legendFormat": "{{api}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "description": "The total number of requests made within' each period",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(api_requests_total{app=\"$app\", service=~\"$service\", env=~\"$env\", api=~\"$api\", protocol=~\"$protocol\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Request latency P99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "api_requests_latency_ms{app=\"$app\",instance=~\"$instance\",service=~\"$service\",region=~\"$region\", az=~\"$az\",api=~\"$api\", protocol=~\"$protocol\", quantile=\"0.99\"}",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Requests / $api-$protocol",
   "type": "timeseries",
   "description": "This is a total number of requests broken down.  This can help get a sense of scale in relation to each other.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(api_requests_total{ app=\"$app\", service=~\"$service\", env=~\"$env\", api=~\"$api\", protocol=~\"$protocol\", instance=~\"$instance\"}[$__interval])) by (api,protocol)",
     "legendFormat": "{{api}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "Status Codes($protocol )",
   "type": "timeseries",
   "description": "The breakdown of the various $protocol  status codes of the requests handled within' this period that matches the variables chosen above.\n\nThis chart helps notice and dive into which service is having failures and of what kind.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(api_requests_total{ app=\"$app\", service=~\"$service\", env=~\"$env\", api=~\"$api\", protocol=~\"$protocol\", instance=~\"$instance\"}[$__interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "MYSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true
  },
  { "title": "Go Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "process memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "{{job}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "{{job}} - virtual"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job=\"$app\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{job}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{job=\"$app\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{job}} - virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$app\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$app\",instance=~\"$instance\",service=~\"$service\"}[30s])",
     "legendFormat": "{{instance}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$app\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$app\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}} - heap inuse"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{job=\"$app\",instance=~\"$instance\",service=~\"$service\"}[5m])",
     "legendFormat": "{{instance}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$app\",instance=~\"$instance\",service=~\"$service\"}[5m])",
     "legendFormat": "{{instance}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{job=\"$app\",instance=~\"$instance\",service=~\"$service\"}[5m])",
     "legendFormat": "{{instance}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{job=\"$app\",instance=~\"$instance\",service=~\"$service\"}[5m])",
     "legendFormat": "{{instance}} - heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "open fds deriv(5m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "deriv(process_open_fds{job=\"$app\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$app\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}: {{quantile}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$app\", instance=~\"$instance\", service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}