syntax = "proto3";

package openapi.v1.docs.example;

option go_package = "protos-repo/example/openapi/v1/user";

import "github.com/asjard/protobuf/http.proto";

import "protos-repo/common/common.proto";

service User {
    // Get retrieves a single user by their primary identifier (username/key).
    // Workflow: LocalCache -> Redis -> Database.
    // Failure to find a record results in a gRPC NOT_FOUND (HTTP 404).
    rpc Get(api.common.ReqWithName) returns (UserInfo) {
        option (asjard.api.http) = {
            get : '/'
        };
        option (asjard.api.http) = {
            get : '/{name}'
        };
    };
}

// UserInfo represents the data structure returned for single or list queries.
message UserInfo {
    // Unique internal system identifier (Snowflake or Auto-increment).
    string username = 2;
    int32  age      = 3;
}
