package main

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/asjard/asjard/pkg/protobuf/validatepb"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

const (
	// FileDescriptorProto.package field number
	fileDescriptorProtoPackageFieldNumber = 2
	// FileDescriptorProto.syntax field number
	fileDescriptorProtoSyntaxFieldNumber = 12
)

const (
	validatorPackage  = protogen.GoImportPath("github.com/go-playground/validator")
	validatepbPackage = protogen.GoImportPath("github.com/asjard/asjard/pkg/protobuf/validatepb")
)

type ValidateGenerator struct {
	plugin *protogen.Plugin
	file   *protogen.File
	gen    *protogen.GeneratedFile
}

func NewValidateGeneratr(plugin *protogen.Plugin, file *protogen.File) *ValidateGenerator {
	return &ValidateGenerator{
		plugin: plugin,
		file:   file,
	}
}

func (g *ValidateGenerator) Run() *protogen.GeneratedFile {
	if len(g.file.Messages) == 0 {
		return nil
	}
	g.gen = g.plugin.NewGeneratedFile(g.file.GeneratedFilenamePrefix+"_validate.pb.go", g.file.GoImportPath)

	g.genLeadingComments(g.file.Desc.SourceLocations().ByPath(protoreflect.SourcePath{fileDescriptorProtoSyntaxFieldNumber}))
	g.gen.P("// Code generated by ", name, ". DO NOT EDIT.")
	g.gen.P("// versions:")
	g.gen.P("// - ", name, " v", version)
	g.gen.P("// - protoc             ", g.protocVersion())
	if g.file.Proto.GetOptions().GetDeprecated() {
		g.gen.P("// ", g.file.Desc.Path(), " is a deprecated file.")
	} else {
		g.gen.P("// source: ", g.file.Desc.Path())
	}
	g.gen.P()

	// Attach all comments associated with the package field.
	g.genLeadingComments(g.file.Desc.SourceLocations().ByPath(protoreflect.SourcePath{fileDescriptorProtoPackageFieldNumber}))
	g.gen.P("package ", g.file.GoPackageName)
	g.gen.P()

	g.genFileContent()
	return g.gen
}

func (g *ValidateGenerator) genFileContent() {
	for _, message := range g.file.Messages {
		g.genMessage(message)
	}
}

func (g *ValidateGenerator) genMessage(message *protogen.Message) {
	g.gen.P("func (m *", message.GoIdent.GoName, ")IsValid(opts ...", validatepbPackage.Ident("ValidaterOption"), ") error{")
	g.gen.P("options := ", validatepbPackage.Ident("ValidaterOptions"), "{}")
	g.gen.P("for _, opt := range opts {")
	g.gen.P("opt(options)")
	g.gen.P("}")
	inited := false
	for _, field := range message.Fields {
		switch field.Desc.Kind() {
		case protoreflect.MessageKind, protoreflect.EnumKind:
			if field.Desc.IsList() {
				g.gen.P("for _, fm := range m.", field.GoName, "{")
				g.gen.P("if err := fm.IsValid(opts...); err != nil {")
				g.gen.P("return err")
				g.gen.P("}")
				g.gen.P("}")

			} else {
				g.gen.P("if err := m.", field.GoName, ".IsValid(opts...); err != nil {")
				g.gen.P("return err")
				g.gen.P("}")
			}
		default:
			if validateRule, ok := proto.GetExtension(field.Desc.Options(), validatepb.E_Validate).(*validatepb.Validate); ok && validateRule != nil {
				rules := strings.Split(validateRule.Rules, ";")
				if len(rules) != 0 {
					if !inited {
						g.gen.P("v := ", validatorPackage.Ident("New"))
						inited = true
					}
					methodRules := make(map[string][]string)
					var globalRules []string
					for _, rule := range rules {
						methodAndRule := strings.Split(rule, ":")
						if len(methodAndRule) == 2 {
							methodRules[methodAndRule[0]] = append(methodRules[methodAndRule[0]], methodAndRule[1])
						} else {
							globalRules = append(globalRules, rule)
						}
					}
					if len(globalRules) != 0 {
						g.gen.P("if err := v.Var(m.", field.GoName, ",", strconv.Quote(strings.Join(globalRules, ",")), "); err != nil {")
						g.gen.P("return err")
						g.gen.P("}")
					}
					for method, rules := range methodRules {
						g.gen.P("if options.FullMethod != \"\" && options.FullMethod == ", strconv.Quote(method), "{")
						g.gen.P("if err := v.Var(m.", field.GoName, ",", strconv.Quote(strings.Join(rules, ",")), "); err != nil {")
						g.gen.P("return err")
						g.gen.P("}")
						g.gen.P("}")
					}
				}
			}
		}
		// g.gen.P("//name=", field.GoName)
		// g.gen.P("//kind=", field.Desc.Kind())
		// g.gen.P("//goIdent=", field.GoIdent)
		// g.gen.P("//parent=", field.Parent)
		// g.gen.P("//oneof=", field.Oneof)
		// g.gen.P("//extendee=", field.Extendee)
		// g.gen.P("//message=", field.Message)
		// g.gen.P("//===========================")
	}
	g.gen.P("return nil")
	g.gen.P("}")
}

func (g *ValidateGenerator) genLeadingComments(loc protoreflect.SourceLocation) {
	for _, s := range loc.LeadingDetachedComments {
		g.gen.P(protogen.Comments(s))
		g.gen.P()
	}
	if s := loc.LeadingComments; s != "" {
		g.gen.P(protogen.Comments(s))
		g.gen.P()
	}
}

func (g *ValidateGenerator) protocVersion() string {
	v := g.plugin.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}
