export BIFROST_DIR ?= ../../third_party/bifrost
export GEN_PROTO_GO_VALIDATE ?= true
export GEN_PROTO_GO_REST ?= true
export GEN_PROTO_GO_REST_GW ?= true
export GEN_PROTO_GO_AMQP ?= true
export PROTO_DIR ?= .
export GEN_PROTO_GO_VALIDATE_OPT ?= validate_enum=true
export PROTOC_OPT ?= "-I../third_party"
# export DEBUG ?= true

-include $(BIFROST_DIR)/Makefile_build
